### ISSUE TITLE
在小程序，Attributify功能，什么时候能支持？

### ISSUE THREAD

**Issue by 729902288** [MellowCo/unocss-preset-weapp#1]
![image](https://user-images.githubusercontent.com/20468762/183279679-70d2954a-0f6f-4bae-837a-34bda230d0d4.png)

**Comment by MellowCo** [comment]
主要是小程序不支持presetAttributify生成的属性选择器[p~="x-4"]，[developers.weixin.qq.com](https://link.juejin.cn/?target=https%3A%2F%2Fdevelopers.weixin.qq.com%2Fminiprogram%2Fdev%2Fframework%2Fcustom-component%2Fwxml-wxss.html%23%25E7%25BB%2584%25E4%25BB%25B6%25E6%25A0%25B7%25E5%25BC%258F)
这个preset只是一个css预设 没有转换功能的 需要这个功能的话 需要通过其他插件转换

**Comment by MellowCo** [comment]
后面有时间 看看

**Comment by MellowCo** [comment]
> ![image](https://user-images.githubusercontent.com/20468762/183279679-70d2954a-0f6f-4bae-837a-34bda230d0d4.png)

试下这个插件 https://github.com/MellowCo/unplugin-unocss-attributify-wechat
