### ISSUE TITLE
升级到v0.55.0之后，类名好像没有自动进行转换？

### ISSUE THREAD

**Issue by fanyuwei4** [MellowCo/unocss-preset-weapp#100]
<img width="441" alt="iShot2023-09-05 14 21 45" src="https://github.com/MellowCo/unocss-preset-weapp/assets/95894653/40d1b4c6-9fd5-4c05-8779-8166543c8885">
上面是v0.54.0版本

**Comment by fanyuwei4** [comment]
<img width="442" alt="iShot2023-09-05 14 21 35" src="https://github.com/MellowCo/unocss-preset-weapp/assets/95894653/728f64a5-ab61-4d0b-a23b-236cdcd31b8e">
在我升级为v0.55.0后，我这样写的#并没有自动转换为_wn_888

**Comment by MellowCo** [comment]
你用的是什么平台，原生小程序吗

**Comment by fanyuwei4** [comment]
> 

uniapp vue2

**Comment by MellowCo** [comment]
好像没什么问题 
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/8f9d5181-a681-4989-aecd-b946bce84c0b)

**Comment by MellowCo** [comment]
最好有个可重现的案例

**Comment by fanyuwei4** [comment]
我是通过unocss的cli命令对文件进行监听，然后生成Uno.css导入到app.vue里面使用的，没有使用vue2的webpack插件，这样是否有问题？但是这样使用在v0.55.0以前是正常的，会进行转换的

**Comment by MellowCo** [comment]
为啥要用cli呢，直接修改源码，感觉破坏性还是很大的

**Comment by MellowCo** [comment]
https://github.com/unocss/unocss/blob/42a57089a6b2686854bbdea4e1ff647070bdfe3e/packages/cli/src/cli-start.ts#L24

加个 `--write-transformed` 就行了哦
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/52725db0-07cd-4972-a142-6becc7d98f63)
