### ISSUE TITLE
在node_modules中的 dark:bg-dark-brand-primary 写法失效

### ISSUE THREAD

**Issue by qinains** [MellowCo/unocss-preset-weapp#103]
```
pnpm i lninl-ui

//uno.config.js文件
import presetWeapp from 'unocss-preset-weapp'
import { extractorAttributify, transformerClass } from 'unocss-preset-weapp/transformer'
import { defineConfig, presetIcons } from 'unocss'
const { presetWeappAttributify, transformerAttributify } = extractorAttributify()

export default defineConfig({
    presets: [
        presetWeapp({ dark: "media" }),
        presetWeappAttributify(),
        presetIcons(),
    ],
    transformers: [
        transformerAttributify(),
        transformerClass(),
    ],
    theme: {
        colors: {
            brand: {
                primary: 'yellow',
                second: 'red'
            },
            dark: {
                brand: {
                    primary: 'blue',
                    second: 'purple'
                }
            }
        }
    },
})
```
```
pages.json 文件中的 easycom/custom为"^l-(.*)": "lninl-ui/components/l-$1/l-$1.vue"
```
此时文件 node_modules/lninl-ui/components/l-tabbar/l-tabbar.vue 中的dark:bg-dark-brand-primary在pnpm run dev:h5 或pnpm run  dev:mp-weixin 都不正常。（编译出来的node-modules/lninl-ui/components/l-tabbar/l-tabbar.wxml为dark:bg-dark-brand-primary，app.wxss为dark_cl_bg-dark-brand-primary，两者不一致）。

如果复制 node_modules/lninl-ui/components/* 到项目的 src/components 目录下，修改
```
pages.json 文件中的 easycom/custom为"^l-(.*)": "./components/l-$1/l-$1.vue"
```
再次运行pnpm run dev:h5 或pnpm run  dev:mp-weixin ，结果是正常的，"dark:bg-dark-brand-primary"写法起作用。

现在结果：node_modules下dark:bg-dark-brand-primary写法失效
期望结果：node_modules下dark:bg-dark-brand-primary写法起作用

**Comment by MellowCo** [comment]
node_modules的文件怎么可以修改呢，这种不确定因素太多了，下载的组件库没有css文件的吗

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass#options

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/c92f7114-1797-41a3-a6fb-b6e55eebd9f6)

**Comment by qinains** [comment]
这个组件库是我自己的写的，也是用unocss来写。现在想统一用unocss来写组件。截图的那两个设置了，也无效

**Comment by qinains** [comment]
[bug103.zip](https://github.com/MellowCo/unocss-preset-weapp/files/13030690/bug103.zip)
下载项目，然后
`pnpm i
pnpm run dev:mp-weixin
`
之后在微信开发者工具中打开项目。
左上角点开“模拟操作”，在“深色/浅色”中切换。正常的话：深色底部看到蓝色，浅色底部看到黄色。

“pages.json 文件中的 easycom/custom为"^l-(.*)": "lninl-ui/components/l-$1/l-$1.vue" ”情况下都是看到黄色，处于异常情况。

**Comment by qinains** [comment]
> https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass#options
> 
> ![image](https://user-images.githubusercontent.com/47939250/275677807-c92f7114-1797-41a3-a6fb-b6e55eebd9f6.png)

之前我设置错了。设置“transformerClass({ exclude: ".git" })”即可正常。
