### ISSUE TITLE
taro webpack5 h5 配置了 baseFontSize = 16 还是按20计算

### ISSUE THREAD

**Issue by swbcnegc** [MellowCo/unocss-preset-weapp#104]
pxtransform: {
        enable: true,
        config: {
          onePxTransform: true,
          baseFontSize: 20
        }
      }

https://github.com/MellowCo/unocss-preset-weapp/blob/main/src/rpxTranform/taro.ts
这里baseFontSize 固定是 20 可以改成从配置读取吗？如果元素没设置大小，继承根节点的font-size: 20px ，会导致h5端和小程序的大小不一致

**Comment by MellowCo** [comment]
这里取得就是taro的转换配置啊

**Comment by swbcnegc** [comment]
> 这里取得就是taro的转换配置啊

export function taroPxToRemW5(size: any, designWidth: any, deviceRatio: any) {
  // taro 的 postcss baseFontSize 为20
  const baseFontSize = 20
  // 保留小数位数
  const unitPrecision = 5
  const rootValue = baseFontSize / deviceRatio[designWidth] * 2

  const pixels = Number.parseFloat(size)
  return `${toFixed((pixels / rootValue), unitPrecision)}rem`
} 

这里不是写死是20了吗，我的意思是能不能 pxtransform 里配置了 baseFontSize 多少就按多少计算

**Comment by MellowCo** [comment]
因为taro默认配置就是20啊

**Comment by MellowCo** [comment]
taro的转换已经包括了h5端和小程序的，基本上是一样的

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/taro_webpack4_vue3#taro-h5%E5%85%BC%E5%AE%B9


https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/taro_webpack4_vue3#taro-h5-%E5%9F%BA%E5%87%86%E5%AD%97%E4%BD%93

**Comment by MellowCo** [comment]
在body上加个 text-base 就解决了元素没设置大小的问题了
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/4cbf2180-858e-40ef-9728-62740d93f6b1)

**Comment by swbcnegc** [comment]
感谢感谢，没翻到这个issues。在html页面加就好了，忘了这只是个样式名。昨天挨个在vue页面加，写傻了 :)
