### ISSUE TITLE
单位使用 upx ？

### ISSUE THREAD

**Issue by Journey98** [MellowCo/unocss-preset-weapp#106]
请问是否有兼容upx的打算，这样一来基本不需要处理rem的情况。这里我只考虑了uniapp，如果把px转为 upx 这样一来基本就不用考虑剩余的逻辑，uniapp自身会对 upx 做出对应的逻辑处理。

**Comment by MellowCo** [comment]
uniapp 早就用rpx当单位了

**Comment by Journey98** [comment]
想请教一个问题，就是为什么在使用指令的时候，uniapp 的处理逻辑对 rpx 单位不生效了呢？ 是因为 unocss 的 transformers 执行晚于 uno 吗
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52627267/3b1f4f5c-1b52-41fb-9f7a-e0961a93cc60)

**Comment by Journey98** [comment]
export default defineConfig({
  //@ts-ignore
  presets: [presetUno(), presetRemToPx(), pxToUpx()],
  transformers: [
    transformerDirectives({
      enforce: 'pre',
    }),
  ],
})
