### ISSUE TITLE
微信小程序原生  pb-safe 规则不识别

### ISSUE THREAD

**Issue by hetao1024768** [MellowCo/unocss-preset-weapp#108]
如题

**Comment by Journey98** [comment]
最好可以贴个代码

```html
<div class="btn-wrapper bottom-[env(safe-area-inset-bottom)]">
      <HexButton2>确定</HexButton2>
 </div> 
```

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52627267/c653c1b9-3287-48c9-8598-dddcad5a935c)

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/blob/d2f03b3f19b975bbd0ebc5979cbe2adb8044ab24/src/rules/safe-area.ts#L4C1-L10

**Comment by MellowCo** [comment]
小程序不支持，那就没办法了

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/45709872-41e8-46a8-8ed7-0682a7b8d18d)
