### ISSUE TITLE
关于 transformer-weapp-class 和  unocss-preset-weapp 的配置项

### ISSUE THREAD

**Issue by Journey98** [MellowCo/unocss-preset-weapp#109]
请教一下, unocss-preset-weapp 设置  options.transform 为 true 的时候, 是不是和   transformer-weapp-class 的工作重复了呢? 我这里发现只要配置了其中一项都可以达到类名转换的条件, 只不过在  transformer-weapp-class 内部处理的时候同时保留了` .w-1/2` 这个类名，然后又在  unocss-preset-weapp 的 postprocess 函数中做了一层处理，想请教一下这个是为什么呢？
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52627267/9d00bad4-d336-401b-a944-d67d8b06862b)

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52627267/4d9047f7-517c-462d-8c4a-96d13fd3c94c)

**Comment by MellowCo** [comment]
preset 是负责转换生成的css的
```css
.w-1/2 {
}
```

transformer 是负责转换源码的
```html
<view classs="w-1/2"></view>
```

**Comment by MellowCo** [comment]
少一个小程序端都会报错

**Comment by Journey98** [comment]
明白了，transformer-weapp-class 修改类名是为了和css的类名关联起来哈哈，傻了傻了。大佬有没有交流群啊
