### ISSUE TITLE
h5运行报错

### ISSUE THREAD

**Issue by yzlhdy** [MellowCo/unocss-preset-weapp#110]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/49674055/8d93384b-271b-44d5-970b-2208e87dd19e)
环境：
 "devDependencies": {
    "@dcloudio/types": "^3.3.2",
    "@dcloudio/uni-automator": "3.0.0-3081220230817001",
    "@dcloudio/uni-cli-shared": "3.0.0-3081220230817001",
    "@dcloudio/uni-stacktracey": "3.0.0-3081220230817001",
    "@dcloudio/vite-plugin-uni": "3.0.0-3081220230817001",
    "@vue/runtime-core": "^3.2.45",
    "@vue/tsconfig": "^0.1.3",
    "typescript": "^4.9.4",
    "unocss": "^0.57.2",
    "unocss-preset-weapp": "^0.57.0",
    "vite": "4.1.4",
    "vue-tsc": "^1.0.24"
  }

**Comment by MellowCo** [comment]
没有问题

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/412dfc53-debe-4e79-9efd-909ace6921db)

**Comment by yzlhdy** [comment]
可以了是一个配置没对,谢谢
