### ISSUE TITLE
编译微信小程序报错

### ISSUE THREAD

**Issue by mojiefong** [MellowCo/unocss-preset-weapp#114]
环境：Node v16.20.2

<img width="796" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/17779577/386e0cb8-f821-4e78-9056-659d37e07e70">

大佬，请教一下，我在编译微信小程序的时候报错
<img width="1439" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/17779577/f0a84380-9095-4665-8a79-81a139472379">

unocss 试过了 46、48、50+ 的版本都不行
仓库在 https://github.com/mojiefong/uniapp-mojie-music 麻烦大佬帮忙看看

**Comment by MellowCo** [comment]
蛮奇怪的，example下vue3的demo和你的差不多，没什么问题
不知道是不是什么包冲突了

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/blob/c1d0e6684d0852edeee10ad17091955da9e375fc/examples/uniapp_vue3/package.json#L1-L68

**Comment by mojiefong** [comment]
感谢大佬，排出问题了，是因为使用了背景图的class `bg-[url(xxx)]` 导致报错的，不知道是不是属于您的bug @MellowCo 

<img width="900" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/17779577/b807210f-f0e0-43f3-94a9-a759d234bb1a">


我测试一下 unocss v0.57.7 和 unocss-preset-weapp  v0.57.1，只要是自定义class 来写背景图也会报错，直接用style内联就可以
unocss v0.58.0 和 unocss-preset-weapp  v0.58.0，自定义class 和 style都可以的

目前都已升级到 v0.58.0 版本了，暂时用style内联解决了

**Comment by MellowCo** [comment]
这个是因为 unocss 生成的是静态css，所以 ~@ 没有被转成对应的地址

**Comment by MellowCo** [comment]
像这个 https://github.com/MellowCo/unocss-preset-weapp/issues/9

**Comment by MellowCo** [comment]
https://github.com/unocss/unocss/discussions/3312
https://github.com/unocss/unocss/discussions/2665

**Comment by mojiefong** [comment]
好的，感谢大佬
