### ISSUE TITLE
您好，请问插件支持 nvue 页面吗？

### ISSUE THREAD

**Issue by kosuke-zhang** [MellowCo/unocss-preset-weapp#115]
对 nvue 有强需求，希望 h5 app app-nvue 小程序原子化 css 都能用

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/blob/main/examples/taro_webpack5_react/unocss.config.ts

```ts
content:{
  pipeline:{
    include: [/\.([jt]sx|css)($|\?)/],
    exclude: []
  }
}
```

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify#include-exclude

```ts
import { transformerAttributify } from 'unocss-preset-weapp/transformer'

transformerAttributify({
  exclude: [/[\\/]node_modules[\\/]/, /[\\/]\.git[\\/]/, /[\\/]my-folder[\\/]/],
  include: [/\.vue$/, /\.vue\?vue/]
})
```

**Comment by MellowCo** [comment]
可以参考这个 添加nvue 试试

**Comment by kosuke-zhang** [comment]
好嘞，感谢！

**Comment by kosuke-zhang** [comment]
暂未验证nvue是否支持，验证后反馈～

**Comment by liujiayii** [comment]
> 暂未验证nvue是否支持，验证后反馈～

请问在nvue里可以用吗？我试了下不行

**Comment by kosuke-zhang** [comment]
> > 暂未验证nvue是否支持，验证后反馈～
> 
> 请问在nvue里可以用吗？我试了下不行

我也没测通，nvue 就直接裸写 css 吧，也挺快
