### ISSUE TITLE
您好，单位能全部设置为rpx吗？

### ISSUE THREAD

**Issue by jiang-jiang-jiang-1** [MellowCo/unocss-preset-weapp#116]
比如mt-2，现在转换为margin-top：16rpx，能否转换为：margin-top：2rpx。

**Comment by MellowCo** [comment]
自己覆盖就行

```ts
rules: [
  [/^m-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })],
],
```

**Comment by jiang-jiang-jiang-1** [comment]
感谢您的解答
`
//unocss.config.ts
import { defineConfig } from 'unocss'

export default defineConfig({
  // 其他配置项...
  rules: [
    [/^m-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })],
  ],
  // 其他配置项...
})`

**Comment by haobarry** [comment]
好多要處理的

**Comment by gitHao914** [comment]
强烈建议自定义单位

**Comment by gitHao914** [comment]
[/^p-?(\d+)$/, ([, d]) => ({ padding: `${d}rpx` })],
		[/^p-?t-?(\d+)$/, ([, d]) => ({ 'padding-top': `${d}rpx` })],
		[/^p-?b-?(\d+)$/, ([, d]) => ({ 'padding-bottom': `${d}rpx` })],
		[/^p-?l-?(\d+)$/, ([, d]) => ({ 'padding-left': `${d}rpx` })],
		[/^p-?r-?(\d+)$/, ([, d]) => ({ 'padding-right': `${d}rpx` })],

		[/^m-?(\d+)$/, ([, d]) => ({ margin: `${d}rpx` })],
		[/^m-?t-?(\d+)$/, ([, d]) => ({ 'margin-top': `${d}rpx` })],
		[/^m-?b-?(\d+)$/, ([, d]) => ({ 'margin-bottom': `${d}rpx` })],
		[/^m-?l-?(\d+)$/, ([, d]) => ({ 'margin-left': `${d}rpx` })],
		[/^m-?r-?(\d+)$/, ([, d]) => ({ 'margin-right': `${d}rpx` })],
目前最全配置项

**Comment by lulal** [comment]
rules: [
    // ========== Margin 边距 ==========
    [/^m-(\d+)$/, ([, d]) => ({ margin: `${d}rpx` })],
    [/^mt-(\d+)$/, ([, d]) => ({ 'margin-top': `${d}rpx` })],
    [/^mb-(\d+)$/, ([, d]) => ({ 'margin-bottom': `${d}rpx` })],
    [/^ml-(\d+)$/, ([, d]) => ({ 'margin-left': `${d}rpx` })],
    [/^mr-(\d+)$/, ([, d]) => ({ 'margin-right': `${d}rpx` })],
    [/^mx-(\d+)$/, ([, d]) => ({ 'margin-left': `${d}rpx`, 'margin-right': `${d}rpx` })],
    [/^my-(\d+)$/, ([, d]) => ({ 'margin-top': `${d}rpx`, 'margin-bottom': `${d}rpx` })],

    // ========== Padding 内边距 ==========
    [/^p-(\d+)$/, ([, d]) => ({ padding: `${d}rpx` })],
    [/^pt-(\d+)$/, ([, d]) => ({ 'padding-top': `${d}rpx` })],
    [/^pb-(\d+)$/, ([, d]) => ({ 'padding-bottom': `${d}rpx` })],
    [/^pl-(\d+)$/, ([, d]) => ({ 'padding-left': `${d}rpx` })],
    [/^pr-(\d+)$/, ([, d]) => ({ 'padding-right': `${d}rpx` })],
    [/^px-(\d+)$/, ([, d]) => ({ 'padding-left': `${d}rpx`, 'padding-right': `${d}rpx` })],
    [/^py-(\d+)$/, ([, d]) => ({ 'padding-top': `${d}rpx`, 'padding-bottom': `${d}rpx` })],

    // ========== Width/Height 宽高 ==========
    [/^min-w-(\d+)$/, ([, d]) => ({ 'min-width': `${d}rpx` })],
    [/^min-h-(\d+)$/, ([, d]) => ({ 'min-height': `${d}rpx` })],
    [/^max-w-(\d+)$/, ([, d]) => ({ 'max-width': `${d}rpx` })],
    [/^max-h-(\d+)$/, ([, d]) => ({ 'max-height': `${d}rpx` })],
    [/^w-full$/, () => ({ width: '100%' })],
    [/^h-full$/, () => ({ height: '100%' })],

    // ========== Position 定位 ==========
    [/^inset-(\d+)$/, ([, d]) => ({ top: `${d}rpx`, right: `${d}rpx`, bottom: `${d}rpx`, left: `${d}rpx` })],

    // ========== Text 文本 ==========
    [/^text-(\d+)$/, ([, d]) => ({ 'font-size': `${d}rpx` })],
    [/^leading-(\d+)$/, ([, d]) => ({ 'line-height': `${d}rpx` })],
    [/^tracking-(\d+)$/, ([, d]) => ({ 'letter-spacing': `${d}rpx` })],

    // ========== Border 边框 ==========
    [/^rounded-(\d+)$/, ([, d]) => ({ 'border-radius': `${d}rpx` })],
    [/^border-(\d+)$/, ([, d]) => ({ 'border-width': `${d}rpx` })],
    [/^border-t-(\d+)$/, ([, d]) => ({ 'border-top-width': `${d}rpx` })],
    [/^border-b-(\d+)$/, ([, d]) => ({ 'border-bottom-width': `${d}rpx` })],
    [/^border-l-(\d+)$/, ([, d]) => ({ 'border-left-width': `${d}rpx` })],
    [/^border-r-(\d+)$/, ([, d]) => ({ 'border-right-width': `${d}rpx` })],

    // ========== Gap 间距 ==========
    [/^gap-(\d+)$/, ([, d]) => ({ gap: `${d}rpx` })],
    [/^gap-x-(\d+)$/, ([, d]) => ({ 'column-gap': `${d}rpx` })],
    [/^gap-y-(\d+)$/, ([, d]) => ({ 'row-gap': `${d}rpx` })],
  ],
