### ISSUE TITLE
类名没有被转换 taro3.6 vue3  v0.56.1

### ISSUE THREAD

**Issue by Bob0911** [MellowCo/unocss-preset-weapp#117]
环境 taro3.6 + vue3
版本 0.56.1
如图
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22430053/1da4d722-353d-430e-90f5-071fe94f2ab3)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22430053/7d424895-883c-4edf-b6f1-8f4437e8da7a)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22430053/292709a9-c726-4292-9358-d66c20c8bc57)
没有将符号转义 而且样式都没有生效

**Comment by MellowCo** [comment]
不支持动态变量

**Comment by Bob0911** [comment]
> 不支持动态变量

这个也不算动态变量吧 。。 unocss原本也是支持的
