### ISSUE TITLE
whRpx 无效

### ISSUE THREAD

**Issue by xztl** [MellowCo/unocss-preset-weapp#118]
我是 demo 配置拷贝的，不设置whRpx时候 p-1是 8rpx, 设置whRpx为 true 也还是 8rpx，vue3 项目，不知道哪里出了问题，
<img width="1009" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/11171790/ba0e8089-9b1e-4a41-aba1-bf840f153e11">

**Comment by xztl** [comment]
看了下，好像只有 w，h 是处理了的，margin，padding 没处理，好吧，我自己处理

**Comment by haobarry** [comment]
靠 原來如此

**Comment by xztl** [comment]
您好，我已收到您的来信，我会尽快回复您！
