### ISSUE TITLE
[ WXSS 文件编译错误] ./app.wxss  unexpected "\" at pos 152029

### ISSUE THREAD

**Issue by xinlei3166** [MellowCo/unocss-preset-weapp#119]
请问这个该怎么处理呢？
写了rule好像没生效呢。

```js
    transformRules: {
        '.': '-dian-',
        '\\': '-xiegang-',
        '\\?': '-wenhao-',
        '?': '-wenhao-',
        '.?': '-wenhao-'
      }
```

图1：
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22881872/3f365390-1578-4f64-93f9-b62bfd4a2d73)

图2：
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22881872/92783dff-daec-4e8b-bf65-a187fbb35502)

**Comment by chengazhen** [comment]
为什么你这边会有转义符的反斜杠 \ 呢? 作者默认的rule就可以覆盖到到特殊字符。我这里理解的是，只要规则能够覆盖到 unocss 的特殊字符就可以吧。

**Comment by chengazhen** [comment]
https://github.com/MellowCo/unplugin-transform-class/blob/280adc13ae1b633c769d061fc7053cf7c5905780/src/utils.ts#L75 这是相关的处理规则，本质上就是用正则来处理的，如果你用了双反写杠就会被识别出来并且删除掉 
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52627267/8edfee5e-06ff-4b4d-b764-b34ff7fe599b)

**Comment by MellowCo** [comment]
不需要写 \
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/c51fa64a-d06c-4d09-ab6a-16a674dc778c)

可以提供下vue的class代码

**Comment by xinlei3166** [comment]
> 不需要写 \ ![image](https://private-user-images.githubusercontent.com/47939250/293321214-c51fa64a-d06c-4d09-ab6a-16a674dc778c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzMzMzQsIm5iZiI6MTcwMzgzMzAzNCwicGF0aCI6Ii80NzkzOTI1MC8yOTMzMjEyMTQtYzUxZmE2NGEtZDA2Yy00ZDA5LWFiNmEtMTZhNjc0ZGM3NzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA2NTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNGQ5MmY2MzY4NWI2ZGYyZjAzZjRhYThkOWYzMzExOTQ2MWEyNWY4ZTM1Zjc0OWI5MzQ2NTUwNGZjNzg2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BvcccHuGoLjQMxyrCwrjp9ndTOU0_WWHxEHX_f0UhSM)
> 
> 可以提供下vue的class代码

你好，这是项目地址：https://github.com/xinlei3166/vite-uniapp-template

pnpm run dev:mp-weixin ，在微信开发者工具中编译，会出现上面报错。

**Comment by xinlei3166** [comment]
@MellowCo 

你好，这是项目地址：https://github.com/xinlei3166/vite-uniapp-template

pnpm run dev:mp-weixin ，在微信开发者工具中编译，会出现上面报错。

**Comment by xinlei3166** [comment]
> 为什么你这边会有转义符的双反斜杠 \ 呢? 作者默认的rule就可以覆盖到到特殊字符。我这里理解的是，只要规则能够覆盖到 unocss 的特殊字符就可以吧。你现在的问题产生原因在下面

可能是我用的别的ui框架产生的。nutui-uniapp

**Comment by MellowCo** [comment]
1. 去除 presetUno 
presetUno 不支持小程序，生成的css有问题

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/6869f5cd-9e00-4a3d-8f42-2ec4ecb531ed)

**Comment by MellowCo** [comment]
2. 小程序不支持 *

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/861dc406-69d0-453d-836f-8c1955d4d52b)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/be83e21c-7d61-48eb-882f-40bdd1a47a44)

**Comment by xinlei3166** [comment]
> 1. 去除 presetUno
>    presetUno 不支持小程序，生成的css有问题
> 
> ![image](https://private-user-images.githubusercontent.com/47939250/293339591-6869f5cd-9e00-4a3d-8f42-2ec4ecb531ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDM4OTUsIm5iZiI6MTcwMzg0MzU5NSwicGF0aCI6Ii80NzkzOTI1MC8yOTMzMzk1OTEtNjg2OWY1Y2QtOWUwMC00YTNkLThmNDItMmVjNGVjYjUzMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA5NTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmOWFmNTdiYmExYTRiNTFhN2Y5ZTg1ZTk0NjQyZWFmMWI4NmQ3MGQwZDU1ZjRjOTI3OWE0MmJlMTM2MDY0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GFE13wwMQa41HYWVMOxceO_h8IbZ10_zhnGqRdX5pS0)
> 
> ```ts
> import { defineConfig, presetAttributify } from 'unocss'
> import presetWeapp from 'unocss-preset-weapp'
> import { extractorAttributify, transformerClass } from 'unocss-preset-weapp/transformer'
> 
> const { presetWeappAttributify, transformerAttributify } = extractorAttributify()
> 
> // https://unocss.dev/interactive/
> export default defineConfig({
>   presets: [
>     // https://github.com/MellowCo/unocss-preset-weapp
>     presetWeapp({ platform: 'uniapp', whRpx: false }),
>     presetWeappAttributify(),
>     presetAttributify({
>       prefix: 'un-',
>       prefixedOnly: false
>     })
>   ],
>   transformers: [
>     // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
>     transformerAttributify(),
>     // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
>     transformerClass()
>   ],
>   // @ts-ignore opacity: active, disabled
>   // rules: [[/^opacity-(active|disabled)$/, ([, d]) => ({ opacity: `var(--van-${d}-opacity)` })]],
>   theme: {
>     colors: {
>       primary: 'var(--nut-primary-color)', // class="bg-primary"
>       primaryEnd: 'var(--nut-primary-color-end)', // class="bg-primaryEnd"
>       success: 'var(--nut-success-color)',
>       danger: 'var(--nut-danger-color)',
>       warning: 'var(-nut-warning-color)',
>       text: 'var(--nut-title-color)',
>       text2: 'var(--nut-title-color2)',
>       text3: 'var(--nut-text-color)',
>       border: 'var(--nut-border-color)',
>       active: 'var(--nut-active-color)',
>       help: 'var(--nut-help-color)',
>       disable: 'var(--nut-disable-color)',
>       required: 'var(--nut-required-color)'
>     }
>   }
> })
> ```

可以了，非常感谢。
