### ISSUE TITLE
presetWeapp 和 transformerClassTS类型错误

### ISSUE THREAD

**Issue by yanbowe** [MellowCo/unocss-preset-weapp#12]
"unocss": "^0.46.4",
"@unocss/webpack": "^0.46.4",
 "unocss-preset-weapp": "^0.2.0",
![image](https://user-images.githubusercontent.com/43030980/200782940-4cb6d9ad-e72d-44b3-a31b-80487e57f9f4.png)
![image](https://user-images.githubusercontent.com/43030980/200783034-ede71909-e043-42c6-a943-7f4ce182bd51.png)

**Comment by b1ngx** [comment]
Taro 需修改 `tsconfig.json` 的 target 为 2018

```
"compilerOptions": {
    "target": "es2018",
}
```

**Comment by yanbowe** [comment]
> "target": "es2018",

还是一样的错误

**Comment by MellowCo** [comment]
我用你的[模版](https://github.com/yanbowe/taro-vue3-pinia) 升到 ^0.46.4，没出现ts错误，可以使用 any 大法试试

```ts
transformers: [
    transformerClass() as any
  ]
```

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/200794130-81971d09-dbd7-403d-8c43-255436280efd.png)

**Comment by yanbowe** [comment]
难道是因为我使用了Volar [Takeover](https://cn.vuejs.org/guide/typescript/overview.html#volar-takeover-mode) 模式？

**Comment by yanbowe** [comment]
> 我用你的[模版](https://github.com/yanbowe/taro-vue3-pinia) 升到 ^0.46.4，没出现ts错误，可以使用 any 大法试试
> 
> ```ts
> transformers: [
>     transformerClass() as any
>   ]
> ```

先用any了

**Comment by MellowCo** [comment]
我把 `unocss/core` 升级到 `0.46.4` 了，用  `unocss-preset-weapp@0.2.1`  试试

**Comment by yanbowe** [comment]
> 我把 `unocss/core` 升级到 `0.46.4` 了，用 `unocss-preset-weapp@0.2.1` 试试

没问题了，可能是我项目pnpm缓存的问题，把node_node_modules和pnpm-lock.yaml删掉重新install就没问题了
