### ISSUE TITLE
使用 :class 绑定类名，中括号会消失

### ISSUE THREAD

**Issue by huage404** [MellowCo/unocss-preset-weapp#120]
项目：uniapp + vue3
依赖：
    - "unocss": "^0.57.1",
    - "unocss-preset-weapp": "^0.56.1",
    
场景：当我使用 :class 动态绑定一个类，例如 w-[100rpx] 是，里面的中括号会消失掉。请问有人遇到和我类似的问题么

**Comment by MellowCo** [comment]
小程序的问题吧

**Comment by MellowCo** [comment]
unocss 不需要写 []

**Comment by huage404** [comment]
我的锅，感谢指点🙏
