### ISSUE TITLE
uni-app 引用uno.css编译报错

### ISSUE THREAD

**Issue by SuperHanMr** [MellowCo/unocss-preset-weapp#121]
uniapp版本:"3.0.0-alpha-3070720230316001"
"unocss": "^0.58.3"
<img width="1557" alt="WechatIMG16" src="https://github.com/MellowCo/unocss-preset-weapp/assets/26862024/dda83f29-5678-4251-80bc-5bda5d4cfb9a">

**Comment by MellowCo** [comment]
你加了preset吗

**Comment by MellowCo** [comment]
unocss.config.js 呢

**Comment by Mrokor** [comment]
解决了吗 我也遇到这种情况
