### ISSUE TITLE
safelist not work if class has transformed symbols

### ISSUE THREAD

**Issue by apm29** [MellowCo/unocss-preset-weapp#122]
# safelist not work if class has transformed symbols
for example, I add some icon class into safelist in unocss.config.js:
```javascript
export default defineConfig({
 //...other config
 
  safelist: [
    "i-mdi:sign-direction","i-mdi:heart","i-mdi:pencil"
  ]
})
```

and add class for view dynamically, for example:
```html
<view  :class="icon" />
```

it not works.

使用unocss-preset-icon,把需要的icon加进safelist,然后再代码中动态添加icon class,icon不会起作用，需要把icon class中的icon都按transform规则转一遍才行

**Comment by MellowCo** [comment]
。。。

**Comment by MellowCo** [comment]
你猜为什么要费劲加transform

**Comment by MellowCo** [comment]
小程序不支持 : / 这些符号啊

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/df92d68f-39ca-452a-a374-04b2f5e9262e)
