### ISSUE TITLE
单位规则 text-32 p-32 单位不一样

### ISSUE THREAD

**Issue by mz-dfhp** [MellowCo/unocss-preset-weapp#123]
<img width="506" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63582593/62083120-1fc9-446b-96a7-5fb8595230b4">
<img width="929" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63582593/19f0f764-730c-49c6-9672-32f9f7ca4b91">

<img width="751" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63582593/822dc209-fcb8-4a9c-8583-740a78808169">

其他按照taro-react demo来的

**Comment by MellowCo** [comment]
p-2 都是按 8 递增的

**Comment by MellowCo** [comment]
text 可以改回 8 递增
https://github.com/MellowCo/unocss-preset-weapp#%E4%BF%AE%E6%94%B9-w-h-%E9%BB%98%E8%AE%A4%E5%8D%95%E4%BD%8D

**Comment by MellowCo** [comment]
也可以自己修改

https://github.com/MellowCo/unocss-preset-weapp/issues/116
