### ISSUE TITLE
使用@unocss/transformer-directives 小程序编译报错

### ISSUE THREAD

**Issue by galileo303** [MellowCo/unocss-preset-weapp#126]
unocss配置可以正常编译，但是使用unocss提供的@unocss/transformer-directives就编译报错
<img width="1028" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/17979785/43cedecc-912c-415f-82a9-63158c4c923f">
使用的是@apply写法
<img width="795" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/17979785/5020aa2a-17ed-4425-af72-75d4d9726bc8">

**Comment by MellowCo** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/58d450c3-305b-4414-9235-e36805ff3405)
