### ISSUE TITLE
在:class中写“bg-[--l-tab-bar-bg-color,theme(backgroundColor.container)]”，解析失效

### ISSUE THREAD

**Issue by qinains** [MellowCo/unocss-preset-weapp#127]
如图
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/528630/6de04e44-97fe-41be-a8a5-afb929f1888c)

如果写在class里边，css的var变量和theme写法解析成功。写在:class里边，则解析失效。
期待结果：写在:class里边，则解析成功。

npm安装
```
npm i @unocss/transformer-directives
npm i @unocss/transformer-variant-group
```

uno.config.js配置如下
```
import presetWeapp from 'unocss-preset-weapp'
import { extractorAttributify, transformerClass } from 'unocss-preset-weapp/transformer'
import { defineConfig, presetIcons } from 'unocss'
import transformerDirectives from '@unocss/transformer-directives'
import transformerVariantGroup from '@unocss/transformer-variant-group'

const { presetWeappAttributify, transformerAttributify } = extractorAttributify()

export default defineConfig({
    presets: [
        // https://github.com/MellowCo/unocss-preset-weapp
        presetWeapp({ dark: "media" }),
        // attributify autocomplete
        presetWeappAttributify(),
        presetIcons(),
    ],
    shortcuts: [{
        "hairline-base": "absolute box-border content-empty pointer-events-none"
    }],
    transformers: [
        transformerDirectives(),
        transformerVariantGroup(),
        // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
        transformerAttributify(),
        // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
        transformerClass({ exclude: ".git" }),
    ],
    theme: {
        colors: {
            "gray-color-3": "var(--l-gray-color-3, #e7e7e7)",
            "font-white-1": "var(--l-font-white-1, rgba(255, 255, 255, 1))",
        },
        backgroundColor: {
            "container": "var(--l-bg-color-container, var(--l-font-white-1, rgba(255, 255, 255, 1)))", // 色彩 - 容器
        },
        borderColor: "var(--l-border-color, var(--l-gray-color-3, #e7e7e7))", // 边框色
    },
})
```

**Comment by MellowCo** [comment]
额 这个怎么用的

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/79902ed0-daee-4024-9d2e-136e6e4c8de8)

**Comment by MellowCo** [comment]
我看了下UNOCSS 能满足好像是这个

https://unocss.dev/play/?html=FAg8BMEsDcAIGMA2BDAzqgvAIgEYHMBaAbQIMQIBdkcCdkAnWw%2BAe0RfoBoKALAUwC2fABR14Aazz0WAVwB24AMJsOAOlZyqkOX3oBKALqwA7gQCMABlg9zFrLAD0APjBQ4SNJlyESZStVoGJgJWdnojX3IqGjpGfBCVegAuXkERMUlpeSVE9RZNZG1dQxNba1t7ZyA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwod6gBccADawRrCbFQwagC0fraoGmRIorbQQRqUyBqKALq5JN5wVAAW0DARMFRBXj4%2B4ZHRIDGl5ZUaGTCmMDG2RHBdJj3QVlhEqHBlAG6oUAGDPV1WtklFCoU%2B-FLVIUWbkrSyEO4AlBt1W7QMTKwcXNyn5-sCMCJinnt1VMLLqEEAjAA6ABMTzqwmQWAyJUYYGqAHp4dQQIDSvDVnVFGcigUijASqgQH9EJ9MaloDtapjqT4AEREKBWbgxclQGIAZlpQVpUysUHcMV6MQZTJZEDSbPZZAAxKgAOzy%2BUnWlgml09AEHoAdxKwC6MX%2BXLgPL5AqFGqw2t1%2Bv%2BZCgRBYVncwIArC6yK73XBPWR-idlaq6utSXVHcIANYMiDaZD4CU1EM02miS1WbCzI0m-mC2wxFhEMUSsWp9NQMi87PmzUxHV61AGu0Op3A0FwdlS71u33%2BgNwRFwQBOQYBLfTgMTggE7tQAWaonFIGfCxoGgoHH0saK2bcwuoEvC9By6ac8LGczWRyZYqFXL-Sq%2B-C4IBO%2BMAYhYDz7BhQnAxAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/5a7a212f-e657-40fa-abff-d0c20308f3ee)

**Comment by MellowCo** [comment]
[theme()功能](https://github.com/unocss/unocss/commit/da5ec2591c962c526db7357669951ca813dccbad
)

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/cec1e1a2-1b8b-4c9b-8a59-1324a6eb4bab)

**Comment by qinains** [comment]
测试代码在下面的test.zip文件中。用vue3，结合unocss如下图，是正确的。
（P.S.在https://unocss.dev/play/中，似乎解析是有问题的，playground中解析不了theme()方法，配置了“import { transformerDirectives, transformerVariantGroup } from 'unocss'”也不行。以test.zip的解析的结果为准）
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/528630/c0f17679-2912-4910-97e3-f828ccda83a3)
[test.zip](https://github.com/MellowCo/unocss-preset-weapp/files/14152183/test.zip)

在"unocss-preset-weapp=0.58.1"版本中，h5解析是正常的，weixin小程序解析不了theme()方法。不知道新版本是否解决了？npmjs上最新版是0.58.1

**Comment by qinains** [comment]
@MellowCo 在h5中解析是正确的，在weixin中解析不了theme()方法，0.58.2版本也存在这个问题

**Comment by MellowCo** [comment]
看了下 这个theme的转换是 [@unocss/transformer-directives](https://unocss.dev/transformers/directives) 的功能，这个应该是转换生成css代码的

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/7b0ed221-92ca-46a3-ad52-fdc6b0aaa4d0)


h5下对生成后的uno.css代码做了2次directives转换，等于是 css属性 -> uno.css -> directives 所以可以使用

小程序下没有触发2次directives转换，只有在初次会转换

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/b7b313e2-af0e-4295-8186-eda79691f23b)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/d5a63150-4798-47b8-9096-7fbbe8c4c915)

应该是 uniapp 的编译问题

**Comment by MellowCo** [comment]
0.58.3 加了一个variable，在规则层面转换 theme()，准备给unocss也提交一个pr看看

**Comment by qinains** [comment]
在"unocss-preset-weapp": "^0.58.3"版本中，还有问题：
问题1：配置transformerClass()后，比如transformerClass({ exclude: ".git" })，theme()函数不全起作用，好像只成功解析vue的第一个theme()函数。
问题2：生成两份css，比如class="shadow-[--l-tab-bar-round-shadow,theme(boxShadow.3)]"会生成：

shadow-_lfl_--l-tab-bar-round-shadow_lco_theme_lbl_boxShadow_dl_3_lbr__lfr_ {
    --un-shadow: var(--l-tab-bar-round-shadow,var(--l-shadow-3, 0 6px 30px 5px rgba(0, 0, 0, 5%), 0 16px 24px 2px rgba(0, 0, 0, 4%), 0 8px 10px -5px rgba(0, 0, 0, 8%)));
    box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
}

.shadow-_lfl_--l-tab-bar-round-shadow_lco_theme_lbl_boxShadow_dl_3_lbr__lfr_ {
    --un-shadow: var(--l-tab-bar-round-shadow,theme(boxShadow.3));
    box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
}
对于问题2，也不是大问题。可能像你说的“uno.css代码做了2次directives转换”的问题

**Comment by MellowCo** [comment]
我加了这么多theme 没问题啊

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/112a08c4-73a8-4693-ab14-0116e954cf9c)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/32e20a35-93b4-43b3-8180-4dedcd6573ac)

**Comment by MellowCo** [comment]
生成两份css 我做了sort了 会以转换后的优先

感觉是 transform 和 variable 的bug，但又找不到原因

**Comment by qinains** [comment]
配置transformerClass()后，比如transformerClass({ exclude: ".git" })，theme()函数不全起作用，如下图生成的css是错误的：
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/528630/2177185e-f021-4a79-9e7f-65d02c23af63)

**Comment by MellowCo** [comment]
多谢反馈 解决这个和生成2次css的问题了

**Comment by qinains** [comment]
完美!辛苦啦 :-D
