### ISSUE TITLE
<view :class="'left-[calc(-1*var(--td-badge-basic-height)+1rpx)]'">test</view>或<view :class="{ [&#124;left-[calc(-1*var(--td-badge-basic-height)+1rpx)]&#124;]: true }">test</view>的写法解析不了

### ISSUE THREAD

**Issue by qinains** [MellowCo/unocss-preset-weapp#128]
问题：```<view :class="'left-[calc(-1*var(--td-badge-basic-height)+1rpx)]'">test</view>```或```<view :class="{ [`left-[calc(-1*var(--td-badge-basic-height)+1rpx)]`]: true }">test</view>```的写法解析不了。
期待结果：以上两种写法能正常解析

**Comment by MellowCo** [comment]
`* + 不在默认转换规则里`
可以自己自定义下，没有的转换规则
https://github.com/MellowCo/unocss-preset-weapp#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99


0.58.6 加到默认转换规则了

**Comment by MellowCo** [comment]
```html
<view :class="'left-[calc(-1*var(--td-badge-basic-height)+1rpx)]'">test</view>
```

这个都属于静态class，没有涉及到动态切换，这个应该写在 class 里，而不是 :class


```html
<view class="left-[calc(-1*var(--td-badge-basic-height)+1rpx)]">
  test
</view>
```

https://eslint.vuejs.org/rules/prefer-separate-static-class.html

![image](https://user-images.githubusercontent.com/47939250/224461636-e45a901c-ec9b-4e01-a630-e772007ba229.gif)

**Comment by MellowCo** [comment]
```html
<view :class="{ [`left-[calc(-1*var(--td-badge-basic-height)+1rpx)]`]: true }">test</view>
```


```html
<view
  :class="[
    1 === 1 ? 'left-[calc(-1*var(--td-badge-basic-height)+1rpx)] left' : 'xxx',
    2 === 2 ? 'right-[calc(-1*var(--td-badge-basic-height)+1rpx)] left' : 'bbb',
    3 === 3 && 'top-[calc(-1*var(--td-badge-basic-height)+1rpx)] left',
  ] "
>
  test
</view>

<view :class="{ 'left-[calc(-1*var(--td-badge-basic-height)+1rpx)]': true }">test</view>
```

**Comment by qinains** [comment]
> ```
> <view :class="'left-[calc(-1*var(--td-badge-basic-height)+1rpx)]'">test</view>
> ```
> 
> 这个都属于静态class，没有涉及到动态切换，这个应该写在 class 里，而不是 :class
> 
> ```
> <view class="left-[calc(-1*var(--td-badge-basic-height)+1rpx)]">
>   test
> </view>
> ```
这里我是有一个class是要用动态的方式写的，下面这里例子完整一些：

 ```
<template>
  <view :class="{
    [`${name} left-[calc(-1*var(--td-badge-basic-height)+1rpx)] relative inline-block v-top`]: 1===1,
  }">test</view>
</template>
<script setup>
import { ref } from "vue"
const name = ref("l-tab-bar")
</script>
 ```

**Comment by MellowCo** [comment]
如果是类名里 存在变量的话 转换不了，只支持静态类名
