### ISSUE TITLE
uni-app vue3 使用unocss后，小程序编译后\未转义，请问是什么问题

### ISSUE THREAD

**Issue by czpalis** [MellowCo/unocss-preset-weapp#130]
"vue": "^3.2.45",
"unocss": "^0.58.5",
"unocss-preset-weapp": "^0.58.6",
uno.config.ts已经按照文档配置了extractorAttributify,和transformerClass 
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/35087025/2009a918-d348-4d23-9f87-773fae8ccda3)

**Comment by MellowCo** [comment]
是哪段代码的问题吧

**Comment by MellowCo** [comment]
看下原代码

**Comment by czpalis** [comment]
我大概测试了一下使用v-if和uni-popup会出现这个问题，// uno.config.ts
import presetWeapp from 'unocss-preset-weapp'
import { extractorAttributify, transformerClass } from 'unocss-preset-weapp/transformer'

const { presetWeappAttributify, transformerAttributify } = extractorAttributify()
import { entriesToCss } from '@unocss/core'
import { theme } from '@unocss/preset-mini'
import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
	presets: [
		presetWeapp(),
		presetWeappAttributify(),
		presetUno(),
	],
	theme: {
		preflightBase: undefined,
		colors: {
			'primary-color': '#FF6B01',
			bgColor: '#F17420',
			buttonColor: '#FF6E1B',
		},
	},
	preflights: [
	  {
	    getCSS: () => {
			const css = entriesToCss(Object.entries(theme.preflightBase!))
			const selector = process.env.UNI_PLATFORM === "mp-weixin" ? "view" : "*";
			return `${selector},::before,::after{${css}}::backdrop{${css}}`
		},
	  },
	],
	rules: [

	],
	shortcuts: {
		'flex-center': 'flex flex-row items-center justify-center',
		'flex-between': 'flex flex-row items-center justify-between',
		'flex-wrap': 'flex flex-row flex-wrap',
		'flex-col-center': 'flex flex-col justify-center items-center',
		'content-none': 'text-sm text-gray absolute top-1/2 left-1/2 transform -translate-1/2'
	},
	transformers: [
		transformerAttributify(),
		transformerClass(),
	]
})

**Comment by MellowCo** [comment]
presetWeapp 包含了 presetmini 的预设的

**Comment by MellowCo** [comment]
是什么缺失了
