### ISSUE TITLE
动态class失效

### ISSUE THREAD

**Issue by Bald-gentleman** [MellowCo/unocss-preset-weapp#131]
你好在模板里使用动态class为啥失效 动态class的值添加不上去  我在模板里也试了确实失效 是我配置的有问题吗
![1710683388639](https://github.com/MellowCo/unocss-preset-weapp/assets/96239344/b7f80eda-b298-43b5-a6ed-7cad240b7fe0)
![1710683400766](https://github.com/MellowCo/unocss-preset-weapp/assets/96239344/bcf6b585-2ce3-43a6-9cc4-1b364f965a46)

**Comment by Bald-gentleman** [comment]
使用 text-#这种方式写的任意颜色值确实不生效

**Comment by haobarry** [comment]
确实 我一般都是用中括号

**Comment by MellowCo** [comment]
```vue
<view :class="[x===1 ? 'c-red' : 'c-blue']">111111111</view>
```
