### ISSUE TITLE
[Vue warn]: Extraneous non-props attributes (option) were passed to component but could not be automatically inherited because component renders fragment or text root nodes

### ISSUE THREAD

**Issue by cloydlau** [MellowCo/unocss-preset-weapp#135]
Keeps showing countless warnings when `whitespace: 'preserve'` (a vue loader option) and `transformerClass` are configured in Taro.

> [Vue warn]: Extraneous non-props attributes (option) were passed to component but could not be automatically inherited because component renders fragment or text root nodes

The warnings disapper if you remove either of them.

Therefore, the warnings might be caused by a conflict between `transformerClass` and `whitespace: 'preserve'`.

Minimal reproduction:
https://github.com/cloydlau/reproduction.git

**Comment by MellowCo** [comment]
how to reproduce

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/0333507f-3bc4-4c2f-b67e-f7fa2b2480e9)

**Comment by MellowCo** [comment]
taro 的编译问题吧，没找到原因，试了下不影响功能

**Comment by cloydlau** [comment]
影响的哈兄弟，我费那么大心思创建这个最小化可复现仓库也是第一为了方便作者排查，第二也是为了确定不是我自己代码的问题。所以你现在看着是只报了一个警告，但实际上在项目中报了几十个，而且是定时报、一直在跳都没法调试了，如果只报一次我都懒得提这个 bug 了。现在我是把 transformerClass 去掉了。

**Comment by cloydlau** [comment]
感谢你对这个仓库的贡献，但是这个问题还是挺有影响的，警告是一直在跳，我把控制台清空后，又会继续跳没完没了的，很影响调试。

**Comment by MellowCo** [comment]
这个参数有什么用呢 移除空格吗

**Comment by MellowCo** [comment]
去掉 warning 不就行了，warning 又不重要
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/e6b19047-f5b0-4f24-aa84-eaaec7ba26a2)
