### ISSUE TITLE
bun 1.1.0 windows版本 下运行报错 selector.replaceAll is not a function

### ISSUE THREAD

**Issue by qinains** [MellowCo/unocss-preset-weapp#136]
测试的项目在这里：[test.zip](https://github.com/MellowCo/unocss-preset-weapp/files/14878607/test.zip)
windows 11下，安装bun
```
powershell -c "irm bun.sh/install.ps1 | iex"
```
之后运行项目：
```
cd test/
bun i
bun run dev:h5
```
然后报错“selector.replaceAll is not a function”

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/528630/e277dc48-8fdb-45bf-8558-f60abed020b6)

**Comment by qinains** [comment]
先卸载掉所有的npm，pnpm等命令

**Comment by MellowCo** [comment]
居然能吧node低版本的问题 带到bun里。。。

**Comment by MellowCo** [comment]
是不是你node版本的问题啊 node14的问题

**Comment by qinains** [comment]
应该不是node的问题，我在命令行下输入node和npm，node和npm是找不到的。我再测试下，升级到bun 1.1.1后又遇到新的问题

**Comment by qinains** [comment]
卸载掉nodejs之后，运行`bun run dev:h5` (bun 为1.1.2版本，unocss-preset-weapp已经升级到最新版："unocss-preset-weapp": "^0.58.8")，发现报错：
```error when starting dev server:
ReferenceError: Cannot access uninitialized variable.
    at interopDefault (D:\repos\uniapp-vue3\node_modules\mlly\dist\index.mjs:2470:33)
    at <anonymous> (D:\repos\uniapp-vue3\node_modules\unconfig\dist\index.mjs:117:34)
    at processTicksAndRejections (:12:39)
error: script "dev:h5" exited with code 1
```
项目直接就启动不了了，不知道是什么回事！
去掉unocss-preset-weapp的相关依赖，项目能够启动

**Comment by qinains** [comment]
卸载掉nodejs之后，运行`bun run dev:h5` (bun 为1.1.2版本，unocss-preset-weapp已经升级到最新版："unocss-preset-weapp": "^0.58.8")，发现报错：
```error when starting dev server:
ReferenceError: Cannot access uninitialized variable.
    at interopDefault (D:\repos\uniapp-vue3\node_modules\mlly\dist\index.mjs:2470:33)
    at <anonymous> (D:\repos\uniapp-vue3\node_modules\unconfig\dist\index.mjs:117:34)
    at processTicksAndRejections (:12:39)
error: script "dev:h5" exited with code 1
```
项目直接就启动不了了，不知道是什么回事！
去掉unocss-preset-weapp的相关依赖，项目能够正常启动

**Comment by MellowCo** [comment]
我不用bun 应该不会花时间搞这个
