### ISSUE TITLE
React项目中，将unocss字符串传递给子组件时，非className字段中的特殊字符异常

### ISSUE THREAD

**Issue by lhz87127855** [MellowCo/unocss-preset-weapp#138]
若传递的unocss不是在className中，则样式中的#丢失，若在className里面则正常
父组件中:
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/4485176/aef6881d-3e43-407c-a4ec-2767c938425b)
子组件中:
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/4485176/d1eb1cf5-60d0-4c08-8834-e0214416159b)
最终渲染：
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/4485176/55cf758d-d1eb-4f45-923c-ee769a6dbdcd)

**Comment by MellowCo** [comment]
这个小程序的问题 小程序直接忽略的

transform 只做了 className 内的转换

**Comment by lhz87127855** [comment]
好的，那这边就不传递非className样式字符串
