### ISSUE TITLE
uniapp_vue2示例demo,h5模式失效

### ISSUE THREAD

**Issue by JMY-2068** [MellowCo/unocss-preset-weapp#14]
![QQ截图20221118152402](https://user-images.githubusercontent.com/80619037/202644934-1ff32fcc-d258-4064-91f3-867d46463cac.png)
在h5上失效

**Comment by MellowCo** [comment]
用这个插件试试 unocss-webpack-uniapp2

https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0

**Comment by JMY-2068** [comment]
> 用这个插件试试 unocss-webpack-uniapp2
> 
> https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0

下载的你提供的示例demo,uniapp_vue2文件夹,使用的确实是unocss-webpack-uniapp2,全都不生效

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/202650526-5b20fce3-b499-4c7d-b4d9-026cc8addc81.png)

这里有添加占位符吗

**Comment by MellowCo** [comment]
我试了下 @unocss/webpack 不生效，unocss-webpack-uniapp2生效

**Comment by JMY-2068** [comment]
> ![image](https://user-images.githubusercontent.com/47939250/202650526-5b20fce3-b499-4c7d-b4d9-026cc8addc81.png)
> 
> 这里有添加占位符吗

![3333](https://user-images.githubusercontent.com/80619037/202651108-b3b91968-2e45-4561-add9-e384c6ac6e9c.png)
我用的你的demo为啥也不行
![163F0913](https://user-images.githubusercontent.com/80619037/202651169-796c88de-1559-4f07-a1a5-18e50bd1eca0.png)

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/202651526-7d053ffb-a171-4080-bf62-5b10103c0cb6.png)
 这个 package 用的什么

**Comment by JMY-2068** [comment]
> ![image](https://user-images.githubusercontent.com/47939250/202651526-7d053ffb-a171-4080-bf62-5b10103c0cb6.png) 这个 package 用的什么

不好意思,我忘记改这个了,demo可以了,但我还是不清楚为什么项目里没生效,这是我的配置
![4444](https://user-images.githubusercontent.com/80619037/202653627-86ab26a6-4bb0-4a21-833a-3205fc6eea6a.png)

**Comment by JMY-2068** [comment]
我好像找到问题了,感谢大佬回复

**Comment by MellowCo** [comment]
啥问题

**Comment by mydracula** [comment]
> 啥问题
我也遇到了demo样式失效的情况，我是uniapp+vue2 不是上面的taro

**Comment by MellowCo** [comment]
> https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0

用这个 https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0，@unocss/webpack 不生效

**Comment by MellowCo** [comment]
> > 啥问题
> > 我也遇到了demo样式失效的情况，我是uniapp+vue2 不是上面的taro

用 这个 https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0, @unocss/webpack 不生效

**Comment by mydracula** [comment]
> > > 啥问题
> > > 我也遇到了demo样式失效的情况，我是uniapp+vue2 不是上面的taro
> 
> 用 这个 https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0, @unocss/webpack 不生效

可以了  我用demo里的package那个软连接有点误导人了  没启起来 谢谢

**Comment by MellowCo** [comment]
> > > > 啥问题
> > > > 我也遇到了demo样式失效的情况，我是uniapp+vue2 不是上面的taro
> > 
> > 
> > 用 这个 https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0, @unocss/webpack 不生效
> 
> 可以了 我用demo里的package那个软连接有点误导人了 没启起来 谢谢

那个是测试用的 QAQ

**Comment by MellowCo** [comment]
看了下，@unocss/webpack 0.45.29 版本，h5下是可以正常使用的，0.45.30更新了 unplugin 插件，load 函数没有加载

**Comment by MellowCo** [comment]
解决方法
* 使用 @unocss/webpack 0.45.29 版本
```shell
yarn add -D unocss @unocss/webpack@0.45.9 unocss-preset-weapp
```

* 使用 [unocss-webpack-uniapp2](https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue2#app-%E5%B0%8F%E7%A8%8B%E5%BA%8F-h5-%E5%B9%B3%E5%8F%B0)
* 2个插件 二选一
