### ISSUE TITLE
请问怎么关闭unocss的属性化，我设置了transformerAttributify没有效果

### ISSUE THREAD

**Issue by wyq0201** [MellowCo/unocss-preset-weapp#141]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/15724790/9ce0010b-0463-46df-bf3b-42b0489c6b46)

使用场景是： 在设置一些组件属性时，比如transiton，block等都会生成css样式
生成了transition这个样式，导致项目无法运行
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/15724790/82c5bb15-9424-4b62-bbc7-fd6f17835d07)

**Comment by MellowCo** [comment]
class 里没有，应该不会生效的吧

**Comment by MellowCo** [comment]
transformerAttributify 是在class里添加类名

生成css是因为 unocss 匹配到了，就生成了

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/8d7d8a49-a952-4c43-a570-8e426e172e21)

**Comment by wyq0201** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/15724790/64498b0b-9434-47ba-92d5-9d303e054488)
我意思是这两个属性也被匹配生成了css，如何设置关闭这个？
而且我还发现就算把代码注释掉，也会被匹配

**Comment by wyq0201** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/15724790/c2e4bc6a-3521-427c-8360-ff7a807057c7)
版本是0.60

**Comment by MellowCo** [comment]
这个是 unocss 匹配到了，不是 preset 的问题，好吧

对这个有疑问，可以去 unocss issue

**Comment by MellowCo** [comment]
生成这个代码，没有在class使用是没有影响的

**Comment by MellowCo** [comment]
unocss的原理是通过正则扫描代码，满足条件就会生成对应的css代码，并不是只匹配class里字符
