### ISSUE TITLE
配置 isH5 为 true 时，编译后的结果有误

### ISSUE THREAD

**Issue by github-lxb** [MellowCo/unocss-preset-weapp#147]
例如：使用 `w-10` 类名，转换后的结果为 `.w-10 {width: %?10?%;}`，附上源码中的截图

![image](https://github.com/user-attachments/assets/b8a2f8ec-fa44-401f-a686-c7711c46ae60)

**Comment by github-lxb** [comment]
使用的是 uniapp ，没看懂这个 isH5 的作用是什么，文档中也没详细提及到

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/blob/main/examples/uniapp_vue3/unocss.config.ts

直接复制
