### ISSUE TITLE
使用 unocss 官方的 transformerVariantGroup 转换器后生成的类名有误

### ISSUE THREAD

**Issue by github-lxb** [MellowCo/unocss-preset-weapp#148]
例如：使用 `hover:(w-50)` ，把 hover 后面的两个括号也转换了，因为使用了 `transformerClass` 转换转义类名，目前转义后的类名为 `hover_cl__lbl_w-50_lbr_`，其中 `(` 被转义为 `_lbl_`，`)` 转义为 `_lbr_`，和生成的css不匹配

**Comment by MellowCo** [comment]
config 文件内容

**Comment by MellowCo** [comment]
看下是不是顺序问题

**Comment by github-lxb** [comment]
> 看下是不是顺序问题

是的，把 `transformerVariantGroup()` 放在 `transformerClass()` 的前面就没问题了，谢谢
