### ISSUE TITLE
unocss@0.46.5, uniapp_vite_vue3，h5打包后 rpx 未转换成 rem

### ISSUE THREAD

**Issue by MellowCo** [MellowCo/unocss-preset-weapp#15]
unocss@0.46.5, build 时 [applyCssTransform](https://github.com/unocss/unocss/pull/1872) 被删除了，导致打包后 rpx 未转换成 rem

**Comment by mydracula** [comment]
> 解决方法: 使用 `0.46.4` 版本
> 
> ```shell
> npm i unocss@0.46.4
> ```

```css
.shadow-md {
    --un-shadow: var(--un-shadow-inset) 0 4px 6px -1px var(--un-shadow-color, rgba(0,0,0,0.1)),var(--un-shadow-inset) 0 2px 4px -2px var(--un-shadow-color, rgba(0,0,0,0.1));
    box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
}
```
为什么我uniapp+vue2的h5被转化成px了， 是正常的么

**Comment by MellowCo** [comment]
> 



> > 解决方法: 使用 `0.46.4` 版本
> > ```shell
> > npm i unocss@0.46.4
> > ```
> 
> ```css
> .h-200 {
>     height: 100px;
> }
> .shadow-md {
>     --un-shadow: var(--un-shadow-inset) 0 4px 6px -1px var(--un-shadow-color, rgba(0,0,0,0.1)),var(--un-shadow-inset) 0 2px 4px -2px var(--un-shadow-color, rgba(0,0,0,0.1));
>     box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
> }
> ```
> 
> 为什么我uniapp+vue2的h5被转化成px了， 是正常的么

这是正常的，这个大小是用 uniapp 内置方法转换的，会根据不同屏幕大小， 改变的

![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)

[uniapp rpxTranform](https://github.com/MellowCo/unocss-preset-weapp/blob/main/src/rpxTranform/uniapp.ts)，在 @dcloudio/vue-cli-plugin-uni/packages/postcss 37行

**Comment by mydracula** [comment]
> > 
> 
> > > 解决方法: 使用 `0.46.4` 版本
> > > ```shell
> > > npm i unocss@0.46.4
> > > ```
> > 
> > 
> > ```css
> > .h-200 {
> >     height: 100px;
> > }
> > .shadow-md {
> >     --un-shadow: var(--un-shadow-inset) 0 4px 6px -1px var(--un-shadow-color, rgba(0,0,0,0.1)),var(--un-shadow-inset) 0 2px 4px -2px var(--un-shadow-color, rgba(0,0,0,0.1));
> >     box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 为什么我uniapp+vue2的h5被转化成px了， 是正常的么
> 
> 这是正常的，这个大小是用 uniapp 内置方法转换的，会根据不同屏幕大小， 改变的
> 
> ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif) [ ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif) ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif) [ ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> 
> [uniapp rpxTranform](https://github.com/MellowCo/unocss-preset-weapp/blob/main/src/rpxTranform/uniapp.ts)，在 @dcloudio/vue-cli-plugin-uni/packages/postcss 37行

那我实际写的时候怎么样根据他的方法转换呢，taro有个尺寸转换的，uniapp我不是很了解

**Comment by MellowCo** [comment]
> 



> > > 
> > 
> > 
> > > > 解决方法: 使用 `0.46.4` 版本
> > > > ```shell
> > > > npm i unocss@0.46.4
> > > > ```
> > > 
> > > 
> > > ```css
> > > .h-200 {
> > >     height: 100px;
> > > }
> > > .shadow-md {
> > >     --un-shadow: var(--un-shadow-inset) 0 4px 6px -1px var(--un-shadow-color, rgba(0,0,0,0.1)),var(--un-shadow-inset) 0 2px 4px -2px var(--un-shadow-color, rgba(0,0,0,0.1));
> > >     box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 为什么我uniapp+vue2的h5被转化成px了， 是正常的么
> > 
> > 
> > 这是正常的，这个大小是用 uniapp 内置方法转换的，会根据不同屏幕大小， 改变的
> > ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >       
> >         [
> >           
> >             ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >           
> >         ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >        [ ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif) ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >       
> >         [
> >           
> >             ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >           
> >         ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> > [uniapp rpxTranform](https://github.com/MellowCo/unocss-preset-weapp/blob/main/src/rpxTranform/uniapp.ts)，在 @dcloudio/vue-cli-plugin-uni/packages/postcss 37行
> 
> 那我实际写的时候怎么样根据他的方法转换呢，taro有个尺寸转换的，uniapp我不是很了解

uniapp 就是按 750rpx 的，没有提供像 taro 的尺寸转换，所以不需要设置

**Comment by MellowCo** [comment]
> > > 
> > 
> > 
> > > > 解决方法: 使用 `0.46.4` 版本
> > > > ```shell
> > > > npm i unocss@0.46.4
> > > > ```
> > > 
> > > 
> > > ```css
> > > .h-200 {
> > >     height: 100px;
> > > }
> > > .shadow-md {
> > >     --un-shadow: var(--un-shadow-inset) 0 4px 6px -1px var(--un-shadow-color, rgba(0,0,0,0.1)),var(--un-shadow-inset) 0 2px 4px -2px var(--un-shadow-color, rgba(0,0,0,0.1));
> > >     box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 为什么我uniapp+vue2的h5被转化成px了， 是正常的么
> > 
> > 
> > 这是正常的，这个大小是用 uniapp 内置方法转换的，会根据不同屏幕大小， 改变的
> > ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >       
> >         [
> >           
> >             ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >           
> >         ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >        [ ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif) ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >       
> >         [
> >           
> >             ![111](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >           
> >         ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/47939250/203484316-f9721410-c9e3-4797-b037-07d24357664b.gif)
> > [uniapp rpxTranform](https://github.com/MellowCo/unocss-preset-weapp/blob/main/src/rpxTranform/uniapp.ts)，在 @dcloudio/vue-cli-plugin-uni/packages/postcss 37行
> 
> 那我实际写的时候怎么样根据他的方法转换呢，taro有个尺寸转换的，uniapp我不是很了解

uniapp 和 小程序一样用 750rpx 的，没有提供像 taro 尺寸转换，所以按 750 设计稿来就行，平常怎么写就怎么写

**Comment by mydracula** [comment]
> > > 那我实际写的时候怎么样根据他的方法转换呢，taro有个尺寸转换的，uniapp我不是很了解
> > 
> > 
> > uniapp 和 小程序一样用 750rpx 的，没有提供像 taro 尺寸转换，所以按 750 设计稿来就行，平常怎么写就怎么写

如果unocss类名的样式被覆盖了比如px-6 怎么让他加个important 我不想在下面写
或者用了UI组件需要深度选择只能在下面写样式了么

**Comment by MellowCo** [comment]
> > > > 那我实际写的时候怎么样根据他的方法转换呢，taro有个尺寸转换的，uniapp我不是很了解
> > > 
> > > 
> > > uniapp 和 小程序一样用 750rpx 的，没有提供像 taro 尺寸转换，所以按 750 设计稿来就行，平常怎么写就怎么写
> 
> 如果unocss类名的样式被覆盖了比如px-6 怎么让他加个important 我不想在下面写 或者用了UI组件需要深度选择只能在下面写样式了么

都是去覆盖原样式的吧，像这样
```css
::v-deep .u-search {
  background-color: red;
}
```

![image](https://user-images.githubusercontent.com/47939250/203669967-66138eb0-6c11-4412-9d35-bd5f656a5593.png)

**Comment by MellowCo** [comment]
> > > 那我实际写的时候怎么样根据他的方法转换呢，taro有个尺寸转换的，uniapp我不是很了解
> > 
> > 
> > uniapp 和 小程序一样用 750rpx 的，没有提供像 taro 尺寸转换，所以按 750 设计稿来就行，平常怎么写就怎么写
> 
> 如果unocss类名的样式被覆盖了比如px-6 怎么让他加个important 我不想在下面写

加 `important`，可以使用 `!` 或 `important:`

```css
.!p-10 {
  padding:80rpx !important;
}

.important:p-3 {
  padding:24rpx !important;
}
```
