### ISSUE TITLE
unplugin-transform-class的package.json中exports没有导出相关的类型文件

### ISSUE THREAD

**Issue by yplxc** [MellowCo/unocss-preset-weapp#150]
没有导出类型文件，引入是ts报找不到模块，不知道作者能否导出呢

**Comment by MellowCo** [comment]
unplugin 是 default 导出的

![image](https://github.com/user-attachments/assets/32002bb7-5d5f-4841-b277-fd67848c093b)

**Comment by yplxc** [comment]
感谢作者，我是用 pnpm 安装的，但是却一直报
无法找到模块“unplugin-transform-class/vite”的声明文件。“D:/study/uniapp-vite-ts-vue3/node_modules/.pnpm/unplugin-transform-class@0.5.3_rollup@4.19.0/node_modules/unplugin-transform-class/dist/vite.mjs”隐式拥有 "any" 类型。
  There are types at 'd:/study/uniapp-vite-ts-vue3/node_modules/unplugin-transform-class/dist/vite.d.ts', but this result could not be resolved when respecting package.json "exports". The 'unplugin-transform-class' library may need to update its package.json or typings 
![1721872329853](https://github.com/user-attachments/assets/f55bf98d-e575-4c0d-a0f9-07561d671be4)

**Comment by MellowCo** [comment]
删除node_module 重装吧，这个应该是你的环境问题

**Comment by yplxc** [comment]
> 删除node_module 重装吧，这个应该是你的环境问题

感谢解答
