### ISSUE TITLE
@unocss/eslint-config的order本来应该是定位在前面的，但transformerClass之后就跑到后面去了

### ISSUE THREAD

**Issue by aaronchen233** [MellowCo/unocss-preset-weapp#151]

**Comment by MellowCo** [comment]
请提供demo

**Comment by aaronchen233** [comment]
[my-demo](https://github.com/aaronchen233/my-demo)
正常排序是这样的
![正常排序](https://github.com/user-attachments/assets/cfe576ac-4c4d-459b-80e7-36efb46343e7)
但使用完小程序预设后排序会变成这样
![Eslint警告](https://github.com/user-attachments/assets/e5dcdaf6-42df-4799-89ba-2092d474b4ad)
Eslint格式化后
![Eslint格式化后](https://github.com/user-attachments/assets/3f3915f2-7be1-477f-9eec-f938d0ab3292)
