### ISSUE TITLE
自定义组件上通过props传递没有转换

### ISSUE THREAD

**Issue by yplxc** [MellowCo/unocss-preset-weapp#152]
vscode代码
![image](https://github.com/user-attachments/assets/a43b2a18-883d-4128-9199-e1efae1097bf)
微信开发者工具
![image](https://github.com/user-attachments/assets/d8ddacb4-adbc-4f14-a861-ebc43003b7fb)

**Comment by MellowCo** [comment]
只转换 class 属性
