### ISSUE TITLE
uniapp vue3 模板无法直接运行

### ISSUE THREAD

**Issue by dbstd2333** [MellowCo/unocss-preset-weapp#154]
uniapp vue3 模板无法直接运行
![image](https://github.com/user-attachments/assets/422d46d8-f62c-4966-800d-d08769400d7c)
提示Error: Cannot find module 'unocss-preset-weapp'

**Comment by MellowCo** [comment]
build 或者 网络连接

![image](https://github.com/user-attachments/assets/acc16fd1-0e88-4ab2-9dc3-391d3157480f)
