### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Jazzzy126** [MellowCo/unocss-preset-weapp#155]
"unocss": "^0.62.3",
    "unocss-preset-weapp": "^0.62.0",
    
    uniapp + vue3
    
![image](https://github.com/user-attachments/assets/37c98079-c151-4ff4-a079-a3fcbe11fac4)

**Comment by Jazzzy126** [comment]
新建一个项目后，按照您的步骤编译又出现其他的错误

![image](https://github.com/user-attachments/assets/145b63ec-69e8-4cfb-93c2-c271e87f294b)

**Comment by MellowCo** [comment]
靠2张图 怎么判断呢

**Comment by MellowCo** [comment]
报错也很明白啊

![image](https://github.com/user-attachments/assets/666003f0-0187-4084-ad9e-912a22ea47e5)

**Comment by Jazzzy126** [comment]
> 报错也很明白啊
> 
> ![图像](https://private-user-images.githubusercontent.com/47939250/362525660-666003f0-0187-4084-ad9e-912a22ea47e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDM3ODAsIm5iZiI6MTcyNDkwMzQ4MCwicGF0aCI6Ii80NzkzOTI1MC8zNjI1MjU2NjAtNjY2MDAzZjAtMDE4Ny00MDg0LWFkOWUtOTEyYTIyZWE0N2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAzNTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYjc5ZDYzNGJlMWE4MWM3MDM5Mzc1NDBjYjQ5NmFjNmU1ZjJiMTkwNjUyNjIzZDliOGRlZGE0NTVlNjc4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qpu7qz-skM6bMjQCucluIso30F8GdrpZvcuUAQFyB5I)

我这边确实是import引入的
![image](https://github.com/user-attachments/assets/ad32da69-c2c6-4ea5-95ef-292df62a0795)

您可以试试这个流程
https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue3

**Comment by MellowCo** [comment]
没有问题啊
![image](https://github.com/user-attachments/assets/47e0969f-3cf7-401c-9684-edb4e04368ff)

**Comment by MellowCo** [comment]
https://github.com/unocss/unocss/issues/3776

**Comment by MellowCo** [comment]
```ts

import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'

// https://vitejs.dev/config/
export default defineConfig(async ()=>{
  const UnoCss = await import('unocss/vite').then(i => i.default)

  return {
    plugins: [
      uni(),
  
      // https://github.com/unocss/unocss
      UnoCss(),
    ],
  }
})
```
