### ISSUE TITLE
Cannot access 'varEmpty' before initialization

### ISSUE THREAD

**Issue by zhangjing007** [MellowCo/unocss-preset-weapp#157]
使用uniapp vue-cli创建的vite项目，在引入本项目后，启动小程序时报错：
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/55d6fe0d-ba95-4334-aba3-2dbd195dacc7">

**Comment by abao-chen** [comment]
临时解决方案：找到报错文件，把varEmpty变量的定义放到文件的最前面
