### ISSUE TITLE
hbuilder创建的这个Vue2版本不生效

### ISSUE THREAD

**Issue by aBigFace** [MellowCo/unocss-preset-weapp#159]
大兄弟，这个hbuilder创建的这个Vue2版本的项目，好像安装你给的文档（vue2脚手架创建的项目）运行起来不生效

![image](https://github.com/user-attachments/assets/04a039a5-cd2b-496a-b40d-a41d3229a3a7)

**Comment by MellowCo** [comment]
没用过 hbuilder

**Comment by MellowCo** [comment]
都是用 cli 生成的

**Comment by aBigFace** [comment]
嗯呐 没办法 我现在换cli了
