### ISSUE TITLE
运行到微信小程序报错

### ISSUE THREAD

**Issue by yanbowe** [MellowCo/unocss-preset-weapp#16]
![image](https://user-images.githubusercontent.com/43030980/203465024-a1b73e15-13af-4783-bc7b-c18bb1560ef5.png)

**Comment by MellowCo** [comment]
是 examples 错误吗

**Comment by yanbowe** [comment]
> 是 examples 错误吗

是的

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/203465571-32988d5b-8155-425a-9162-243fef69bfb2.png)

这个link是啥

**Comment by MellowCo** [comment]
奇怪了 其他项目能正常使用吗 我在 window 上没出现错误

**Comment by yanbowe** [comment]
> 奇怪了 其他项目能正常使用吗 我在 window 上没出现错误

我的模板项目里也是报错，那应该是mac下独有的错误？

**Comment by MellowCo** [comment]
我把本地 lock 文件删除，重新install，出现了同样问题 https://github.com/NervJS/taro/issues/12869

**Comment by yanbowe** [comment]
> 

我也是重新安装的，今天重新install的貌似都出现了问题，估计是taro的问题，我把代码回退到2个月前的版本也不行

**Comment by MellowCo** [comment]
我用 taro 官方的 cli 创建项目，也是同样问题，可能是什么依赖的问题

**Comment by yanbowe** [comment]
> 我用 taro 官方的 cli 创建项目，也是同样问题，可能是什么依赖的问题

已解决，taro给出了个临时解决方案

**Comment by magicyan1** [comment]
> > 我用 taro 官方的 cli 创建项目，也是同样问题，可能是什么依赖的问题
> 
> 已解决，taro给出了个临时解决方案

怎么解决的，找了一圈了，没一个有用的

**Comment by MellowCo** [comment]
> > > 我用 taro 官方的 cli 创建项目，也是同样问题，可能是什么依赖的问题
> > 
> > 
> > 已解决，taro给出了个临时解决方案
> 
> 怎么解决的，找了一圈了，没一个有用的

这是之前一个依赖的问题，更新下依赖就行了
