### ISSUE TITLE
0.64.0 Update Breaks Gradient Rendering with "in oklch" Keywords Added

### ISSUE THREAD

**Issue by lanseria** [MellowCo/unocss-preset-weapp#164]
**Description / 问题描述**:

After updating to version 0.64.0, gradients in my project stopped rendering correctly. I noticed that the keywords "in oklch" appeared unexpectedly, which seems to interfere with the gradient rendering functionality.

在更新到 0.64.0 版本后，项目中的渐变效果无法正确渲染。我发现多出了 "in oklch" 关键字，似乎干扰了渐变渲染功能。

**Steps to Reproduce / 复现步骤**:
1. Update to version 0.64.0.
2. Use gradient settings that previously worked in earlier versions.
3. Observe the gradient rendering and note the "in oklch" keywords in the output.

   更新到 0.64.0 版本  
   使用先前版本中正常工作的渐变设置  
   观察渐变渲染，注意输出中出现的 "in oklch" 关键字  

**Expected Behavior / 预期行为**:  
The gradient should render as it did in previous versions, without the "in oklch" keywords affecting the result.

渐变应当按照先前版本的效果渲染，不受 "in oklch" 关键字影响。

**Actual Behavior / 实际行为**:  
The gradient rendering is disrupted, with "in oklch" keywords seemingly interfering with the display.

渐变渲染被打乱，"in oklch" 关键字似乎影响了显示。

**Environment / 环境**:  
- Version: 0.64.0  
- Affected Feature: Gradient rendering  

**Screenshots / 截图**:  
![image](https://github.com/user-attachments/assets/f5ee4311-881d-45e6-9960-e2fc5dc93bee)

**Comment by MellowCo** [comment]
use 0.64.1
