### ISSUE TITLE
[Feature Request]: 支持 space 规则

### ISSUE THREAD

**Issue by BeanWei** [MellowCo/unocss-preset-weapp#17]
> 感谢开源，原子css用在小程序上很爽，是提高生产力的利器

不知道有没有计划支持这个规则 😄 
Refer: 
https://github.com/unocss/unocss/blob/main/packages/preset-wind/src/rules/spacing.ts
https://tailwindcss.com/docs/space

**Comment by MellowCo** [comment]
加上了，升级到 0.2.4，试下

[demo地址](https://playful-gumption-4bb42b.netlify.app/#/pages/space/index)

**Comment by BeanWei** [comment]
@MellowCo  奈斯~ ❤
