### ISSUE TITLE
presetWeapp、transformerAttributify、transformerClass ts报错

### ISSUE THREAD

**Issue by Asplitline** [MellowCo/unocss-preset-weapp#19]
# 问题描述

实际情况：presetWeapp、transformerAttributify、transformerClass ts报错。
h5 能正常使用 unocss，android 和 wx小程序均不能正常使用

同 [#12 ](https://github.com/MellowCo/unocss-preset-weapp/issues/12)，但dcloudio用的是官方最新版 "3.0.0-alpha-3061020221121002"

# 相关信息

## 开发环境
```bash
nodejs  # v16.18.1
pnpm  # v7.18.1
hbuilderx  # v3.6.5.20221121
```
## package.json

```json
  "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3061020221121002",
  "typescript": "^4.8.4",
  "unocss": "^0.47.5",
  "unocss-preset-weapp": "^0.2.4",
  "vite": "^3.2.4"
```

# 错误信息

presetWeapp - ts报错信息
![image](https://user-images.githubusercontent.com/30248521/206489221-bb7d24bd-4943-4edd-bbc1-de80dd826c55.png)

transformerAttributify - ts报错信息
![image](https://user-images.githubusercontent.com/30248521/206489758-0b29c712-4a84-420a-8ba6-14da080c0f03.png)

transformerClass - ts报错信息
![image](https://user-images.githubusercontent.com/30248521/206489640-a059df46-4d07-4fe7-9f2c-d147f9301fd1.png)

复现代码：https://github.com/Asplitline/uniappv3-template

**Comment by MellowCo** [comment]
unocss 0.47.0 版本好像在 uniapp vite上失效了, 用0.46.5

```shell
npm install unocss@0.46.5
```

**Comment by MellowCo** [comment]
可能和这个提交有关 https://github.com/unocss/unocss/releases/tag/v0.47.0
![image](https://user-images.githubusercontent.com/47939250/206601918-2fdae7a6-5003-48b5-8c33-557aaa62b4bb.png)

**Comment by Asplitline** [comment]
> unocss 0.47.0 版本好像在 uniapp vite上失效了, 用0.46.5
> 
> ```shell
> npm install unocss@0.46.5
> ```

感谢，问题已解决。

**Comment by MellowCo** [comment]
用 `unocss@0.46.4` 吧， 0.46.5 h5打包，`rpx` 没转换成 `rem`

**Comment by terranc** [comment]
这个问题的结论意思是目前还不能用unocss@5是吧？

**Comment by MellowCo** [comment]
> 这个问题的结论意思是目前还不能用unocss@5是吧？

可以使用 uniapp已经更新了

**Comment by terranc** [comment]
![image](https://user-images.githubusercontent.com/224353/232944188-f1879ee3-c5cb-4263-9db5-beb21f01426c.png)
![image](https://user-images.githubusercontent.com/224353/232944155-233491b0-e527-4f95-a6d3-693da23fbaa9.png)
![image](https://user-images.githubusercontent.com/224353/232944356-c9148fa6-f088-4660-baaf-9713495dd4b9.png)


我这还是报这样类似的错误，如果unocss.config里移除相关的几行，就没这个错误了。你说的uniapp已更新是需要操作什么吗？
@MellowCo

**Comment by MellowCo** [comment]
ts的问题 加个 as any 跳过就行

**Comment by MellowCo** [comment]
> ![image](https://user-images.githubusercontent.com/224353/232944188-f1879ee3-c5cb-4263-9db5-beb21f01426c.png) ![image](https://user-images.githubusercontent.com/224353/232944155-233491b0-e527-4f95-a6d3-693da23fbaa9.png) ![image](https://user-images.githubusercontent.com/224353/232944356-c9148fa6-f088-4660-baaf-9713495dd4b9.png)
> 
> 我这还是报这样类似的错误，如果unocss.config里移除相关的几行，就没这个错误了。你说的uniapp已更新是需要操作什么吗？ @MellowCo

ts的问题 加个 as any 跳过就行

https://github.com/MellowCo/unocss-preset-weapp/issues/12

**Comment by terranc** [comment]
@MellowCo got it
