### ISSUE TITLE
unocss@0.47.0 后，uniapp vite 失效

### ISSUE THREAD

**Issue by MellowCo** [MellowCo/unocss-preset-weapp#20]
![image](https://user-images.githubusercontent.com/47939250/206602290-f0d977cc-f165-4a84-85b6-979a93cc189d.png)

**Comment by MellowCo** [comment]
可能和这个提交有关 https://github.com/unocss/unocss/releases/tag/v0.47.0
![image](https://user-images.githubusercontent.com/47939250/206602380-db4f2bd1-7fd4-4bbe-ad75-7b52ff08fc14.png)

**Comment by MellowCo** [comment]
解决方案：使用 0.46.5 版本
```shell
npm install unocss@0.46.5
```

**Comment by MellowCo** [comment]
目前需要等待 uniapp 解决，[uniapp issues](https://github.com/dcloudio/uni-app/issues/4061)

**Comment by MellowCo** [comment]
解决方案：`unocss` 在 `0.47.0` 之后版本，请更新 `uniapp` 版本，目前使用 `3.0.0-alpha-3061620221230001`，问题已经解决

![image](https://user-images.githubusercontent.com/47939250/210128185-b30c3d1d-ca3d-48c6-b14b-d0ae35b5fd9b.png)

**Comment by MellowCo** [comment]
如果不想更新 `uniapp` 版本，`unocss` 请使用 `0.46.4`

```shell
npm install unocss@0.46.4
```

**Comment by popdo** [comment]
目前2023年01月10日 uniapp最新的`3.0.0-alpha-3061620230109001`版本依然不行。
unocss看来暂时只能用0.46x了

**Comment by MellowCo** [comment]
> 目前2023年01月10日 uniapp最新的`3.0.0-alpha-3061620230109001`版本依然不行。 unocss看来暂时只能用0.46x了

用这个版本吧 3.0.0-alpha-3061620230106001，可以在这个 [issues](https://github.com/dcloudio/uni-app/issues/4061) 反馈
