### ISSUE TITLE
有的尺寸会*8，有的不会，造成单位不统一

### ISSUE THREAD

**Issue by doufather** [MellowCo/unocss-preset-weapp#21]
比如p-5生成padding:40rpx
但是bottom-5只会生成bottom:5rpx

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp#%E4%BF%AE%E6%94%B9-w-h-%E9%BB%98%E8%AE%A4%E5%8D%95%E4%BD%8D

看这个
