### ISSUE TITLE
isH5打开后生成的代码为乱码

### ISSUE THREAD

**Issue by doufather** [MellowCo/unocss-preset-weapp#22]
<view class="px-5">

.px-5 {
  padding-left: %?40?%;
  padding-right: %?40?%;
}

**Comment by MellowCo** [comment]
你是什么平台 uniapp vue2 ？

**Comment by doufather** [comment]
uniapp vue3

**Comment by MellowCo** [comment]
uniapp vue3 配置按这个，不用设置 isH5

https://github.com/MellowCo/unocss-preset-weapp/blob/main/examples/uniapp_vue3/unocss.config.ts

**Comment by MellowCo** [comment]
配置文档
https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue3#uni-app-vue3

**Comment by doufather** [comment]
export default defineConfig({
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp()
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      center: 'flex justify-center items-center',
      fxs: 'flex justify-between items-center',
      fxa: 'flex items-center',
      'fxs-col': 'flex flex-col justify-between'
    }
  ],
  transformers: [
    // options https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify(),

    // options https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass()
  ]
})

这是我的配置，但是build:h5出来的单位是rpx，在浏览器上无法正常运行

**Comment by MellowCo** [comment]
unocss 版本是多少

**Comment by doufather** [comment]
0.46.5

**Comment by MellowCo** [comment]
用 0.46.4 试试

**Comment by MellowCo** [comment]
现在有个尴尬的问题，`unocss@0.46.5` h5打包有问题，`unocss@0.47.0` 小程序不生效，。。。

**Comment by doufather** [comment]
好的，我试试

**Comment by doufather** [comment]
可以了，谢谢

**Comment by doufather** [comment]
可以了，谢谢
