### ISSUE TITLE
微信小程序不支持@apply

### ISSUE THREAD

**Issue by zh-neng** [MellowCo/unocss-preset-weapp#24]
微信小程序不支持  @apply
![image](https://user-images.githubusercontent.com/24434147/208296795-e01eb911-0eb1-4cc6-9072-25d7589d9399.png)

**Comment by MellowCo** [comment]
没问题啊
![image](https://user-images.githubusercontent.com/47939250/209416533-09951795-2434-49b5-b17b-d1d52db75853.png)

你用导入 @apply 的 transformer 吗，https://github.com/unocss/unocss/tree/main/packages/transformer-directives

**Comment by MellowCo** [comment]
看了下 [transformer-directives](https://github.com/unocss/unocss/tree/main/packages/transformer-directives) 应该只支持 `vite` ，`webpack` 不支持
