### ISSUE TITLE
uniapp更新后还是无效

### ISSUE THREAD

**Issue by xiaochong44** [MellowCo/unocss-preset-weapp#26]
我已经更新了uniapp，还是无效
![image](https://user-images.githubusercontent.com/25057951/211033943-9f929d32-8205-4bb5-a73e-492d85ac45da.png)
![image](https://user-images.githubusercontent.com/25057951/211033984-2b97a135-6d73-437d-8d22-20fbb3c4adda.png)

**Comment by MellowCo** [comment]
没问题啊

![image](https://user-images.githubusercontent.com/47939250/211226216-14b3e022-526d-43d0-b1dd-4db2692be2cc.png)

**Comment by xiaochong44** [comment]
我这不知道为啥就是不行，没有样式，搞不清楚原因被近换成mini-program-tailwind了

**Comment by xiaochong44** [comment]
我这不知道为啥就是不行，没有样式，搞不清楚原因被近换成mini-program-tailwind了
