### ISSUE TITLE
作者你好，main.js引入 import 'uno.css'，导致在微信上打开H5页面无法渲染。

### ISSUE THREAD

**Issue by hiddendeer** [MellowCo/unocss-preset-weapp#27]
"@dcloudio/uni-app": "3.0.0-3061520221228001",
  "vite": "3.2.4",
    "sass": "^1.50.0",
    "unocss": "^0.48.0",

用的都是最新版本，在其它浏览器上看都是正常的，只有微信上打开这个h5页面只要有 import 'uno.css'，就是空白页。
用了vconsole也没看到报错。

**Comment by MellowCo** [comment]
这个是微信内置浏览器的兼容问题
 https://github.com/unocss/unocss/issues/2031

**Comment by hiddendeer** [comment]
> 这个是微信内置浏览器的兼容问题 [unocss/unocss#2031](https://github.com/unocss/unocss/issues/2031)

有测试过，build打包后放在线上服务器上，微信上打开H5能生效吗，因为这个问题要只是存在开发阶段还好，要是放在线上，通过微信再空白，就是大问题啦

**Comment by MellowCo** [comment]
build 之后可以的，你可以自己 serve 一个服务测试的

**Comment by hiddendeer** [comment]
> build 之后可以的，你可以自己 serve 一个服务测试的

好的，非常感谢

**Comment by MellowCo** [comment]
unocss@0.48.4 已经解决这个问题

[参考这个配置](https://github.com/MellowCo/unocss-preset-weapp#%E5%BC%80%E5%8F%91%E6%97%B6%E5%BE%AE%E4%BF%A1%E7%AD%89%E6%B5%8F%E8%A7%88%E5%99%A8%E7%99%BD%E5%B1%8F%E9%97%AE%E9%A2%98)
