### ISSUE TITLE
您好，按照文档引入后，vscode无法代码提示

### ISSUE THREAD

**Issue by levi-Ma** [MellowCo/unocss-preset-weapp#28]
![image](https://user-images.githubusercontent.com/37390166/212448472-c55fc5a9-1b37-4c14-b177-feebd472fc59.png)
![image](https://user-images.githubusercontent.com/37390166/212448483-9b176984-60e1-437d-9de6-b10a0cab88bb.png)
![image](https://user-images.githubusercontent.com/37390166/212448493-20354d12-57b1-4655-a491-af8c16885d3d.png)

**Comment by MellowCo** [comment]
这个你要看下 unocss 这个插件的控制台输入了什么

![image](https://user-images.githubusercontent.com/47939250/212459679-e369f0d8-383a-4b31-ac00-26ee40b3a0e0.png)

**Comment by levi-Ma** [comment]
感谢，工作区其他项目混杂了

**Comment by levi-Ma** [comment]
工作区的其他项目没有使用unocss，导致检查无法通过，有什么办法可以解决吗？

**Comment by MellowCo** [comment]
没用过工作区哎 试下这个配置？

![image](https://user-images.githubusercontent.com/47939250/212503833-426d0355-10f7-46b7-ba85-86c37e2bc984.png)
