### ISSUE TITLE
taro + vue3 编译不会把px转化为rem或rpx响应式单位

### ISSUE THREAD

**Issue by yanbowe** [MellowCo/unocss-preset-weapp#3]
复现仓库
https://github.com/yanbowe/taro-vue3-pinia

编译到h5或小程序均不会转化为响应式单位
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/43030980/186339628-0dec5fe2-ede2-4005-b608-f711b8cdfccc.png">

**Comment by MellowCo** [comment]
use rpx

**Comment by MellowCo** [comment]
我只对 rpx 做了 响应式单位 转换

**Comment by yanbowe** [comment]
> use rpx

text-20rpx吗？那这样是不是就只能用在小程序编译了

**Comment by MellowCo** [comment]
会根据 h5 和 小程序，转换
![image](https://user-images.githubusercontent.com/47939250/186354143-57c5c919-2886-41cf-bea1-fbd00f6b8e0a.png)
![image](https://user-images.githubusercontent.com/47939250/186354397-215cb6de-9d6b-4699-89ef-561b9c8911b9.png)

**Comment by yanbowe** [comment]
> 会根据 h5 和 小程序，转换
> ![image](https://user-images.githubusercontent.com/47939250/186354143-57c5c919-2886-41cf-bea1-fbd00f6b8e0a.png)
> ![image](https://user-images.githubusercontent.com/47939250/186354397-215cb6de-9d6b-4699-89ef-561b9c8911b9.png)

好的谢谢，不过可以像taro一样把px转换为对应的单位吗😂

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/186354883-6ef309fc-2feb-44ad-831d-9116aaec9559.png)
![image](https://user-images.githubusercontent.com/47939250/186356619-7af52cd8-3555-4866-a7c8-116babe07e53.png)

突然发现，小程序里的 rpx 是以750为标准，taro通过postcss修改css的，小程序里 unocss 生成的css没有经过  designWidth 😂

**Comment by yanbowe** [comment]
> ![image](https://user-images.githubusercontent.com/47939250/186354883-6ef309fc-2feb-44ad-831d-9116aaec9559.png) ![image](https://user-images.githubusercontent.com/47939250/186356619-7af52cd8-3555-4866-a7c8-116babe07e53.png)
> 
> 突然发现，小程序里的 rpx 是以750为标准，taro通过postcss修改css的，小程序里 unocss 生成的css没有经过 designWidth 😂

好像是的，看着大小表现不一致

**Comment by MellowCo** [comment]
taro h5 和 小程序的 rpx 转换不一致的吗。。。
## 小程序
![image](https://user-images.githubusercontent.com/47939250/186405990-26778148-981c-4aad-8466-b4adb734b69b.png)

## h5
![image](https://user-images.githubusercontent.com/47939250/186406299-70319832-7c8a-4f04-b44d-195cabba589f.png)

**Comment by yanbowe** [comment]
> 

taro h5看着是直接把rpx当成px去转化成rem了

**Comment by MellowCo** [comment]
taro 根字体不同版本还不同的 。。。
https://github.com/NervJS/taro/issues/12361

**Comment by MellowCo** [comment]
> taro 根字体不同版本还不同的 。。。 [NervJS/taro#12361](https://github.com/NervJS/taro/issues/12361)

我说为什么 两边字体大小不同 。。。

**Comment by MellowCo** [comment]
升级到 0.1.11
* 针对 taro 将 px 转化为 rem 或 rpx 响应式单位
* deviceRatio: px 设计稿尺寸换算规则
* taroWebpack: 针对 webpack4 和 webpack5 rem 不同，指定 rem 策略
```ts
presetWeapp(
      // 375 标准
      {
        isH5: process.env.TARO_ENV === 'h5',
        platform: 'taro',
        designWidth: 375,
        deviceRatio: {
          375: 2 / 1,
          750: 1,
        },
        taroWebpack: 'webpack5'
      }
    ),
```

**Comment by MellowCo** [comment]
> 640 的标准，应该没什么问题了
* config/index.js
```js
const config = {
  projectName: 'Taro3',
  date: '2021-12-18',
  designWidth: 640,
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
    375: 2 / 1
  },
}
```
* unocss.config.ts
```ts
    presetWeapp({
      // h5兼容
      isH5: process.env.TARO_ENV === 'h5',
      platform: 'taro',
      designWidth: 640,
      deviceRatio: {
        640: 2.34 / 2,
        750: 1,
        828: 1.81 / 2,
        375: 2 / 1
      },
      taroWebpack: 'webpack5'
    })
```

![image](https://user-images.githubusercontent.com/47939250/186549984-de3a17a3-9811-4c48-8cf5-4d2860cdf03f.png)
![image](https://user-images.githubusercontent.com/47939250/186550819-d972c553-f326-4f89-ba03-0649296f9995.png)

**Comment by yanbowe** [comment]
> > 640 的标准，应该没什么问题了
> 
> * config/index.js
> 
> ```js
> const config = {
>   projectName: 'Taro3',
>   date: '2021-12-18',
>   designWidth: 640,
>   deviceRatio: {
>     640: 2.34 / 2,
>     750: 1,
>     828: 1.81 / 2,
>     375: 2 / 1
>   },
> }
> ```
> 
> * unocss.config.ts
> 
> ```ts
>     presetWeapp({
>       // h5兼容
>       isH5: process.env.TARO_ENV === 'h5',
>       platform: 'taro',
>       designWidth: 640,
>       deviceRatio: {
>         640: 2.34 / 2,
>         750: 1,
>         828: 1.81 / 2,
>         375: 2 / 1
>       },
>       taroWebpack: 'webpack5'
>     })
> ```
> 
> ![image](https://user-images.githubusercontent.com/47939250/186549984-de3a17a3-9811-4c48-8cf5-4d2860cdf03f.png) ![image](https://user-images.githubusercontent.com/47939250/186550819-d972c553-f326-4f89-ba03-0649296f9995.png)

那设计稿是375的话，也是需要设置成640吗？

**Comment by MellowCo** [comment]
> > > 640 的标准，应该没什么问题了
> > 
> > 
> > 
> > * config/index.js
> > 
> > ```js
> > const config = {
> >   projectName: 'Taro3',
> >   date: '2021-12-18',
> >   designWidth: 640,
> >   deviceRatio: {
> >     640: 2.34 / 2,
> >     750: 1,
> >     828: 1.81 / 2,
> >     375: 2 / 1
> >   },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * unocss.config.ts
> > 
> > ```ts
> >     presetWeapp({
> >       // h5兼容
> >       isH5: process.env.TARO_ENV === 'h5',
> >       platform: 'taro',
> >       designWidth: 640,
> >       deviceRatio: {
> >         640: 2.34 / 2,
> >         750: 1,
> >         828: 1.81 / 2,
> >         375: 2 / 1
> >       },
> >       taroWebpack: 'webpack5'
> >     })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/47939250/186549984-de3a17a3-9811-4c48-8cf5-4d2860cdf03f.png) ![image](https://user-images.githubusercontent.com/47939250/186550819-d972c553-f326-4f89-ba03-0649296f9995.png)
> 
> 那设计稿是375的话，也是需要设置成640吗？

和 taro config 里的保持一致就行，我只是用 640 测试了下

**Comment by yanbowe** [comment]
> > > > 640 的标准，应该没什么问题了
> > > 
> > > 
> > > 
> > > * config/index.js
> > > 
> > > ```js
> > > const config = {
> > >   projectName: 'Taro3',
> > >   date: '2021-12-18',
> > >   designWidth: 640,
> > >   deviceRatio: {
> > >     640: 2.34 / 2,
> > >     750: 1,
> > >     828: 1.81 / 2,
> > >     375: 2 / 1
> > >   },
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * unocss.config.ts
> > > 
> > > ```ts
> > >     presetWeapp({
> > >       // h5兼容
> > >       isH5: process.env.TARO_ENV === 'h5',
> > >       platform: 'taro',
> > >       designWidth: 640,
> > >       deviceRatio: {
> > >         640: 2.34 / 2,
> > >         750: 1,
> > >         828: 1.81 / 2,
> > >         375: 2 / 1
> > >       },
> > >       taroWebpack: 'webpack5'
> > >     })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://user-images.githubusercontent.com/47939250/186549984-de3a17a3-9811-4c48-8cf5-4d2860cdf03f.png) ![image](https://user-images.githubusercontent.com/47939250/186550819-d972c553-f326-4f89-ba03-0649296f9995.png)
> > 
> > 
> > 那设计稿是375的话，也是需要设置成640吗？
> 
> 和 taro config 里的保持一致就行，我只是用 640 测试了下

谢谢大佬，375测试了一下也可以了👍

**Comment by MellowCo** [comment]
你是mac电脑，@unocss/webpack 0.45.8 之后，unocss 会不生成 css 代码
https://github.com/unocss/unocss/issues/1455
难道是 windows 特有的 bug 吗 😂

**Comment by yanbowe** [comment]
> 你是mac电脑，@unocss/webpack 0.45.8 之后，unocss 会不生成 css 代码 [unocss/unocss#1455](https://github.com/unocss/unocss/issues/1455) 难道是 windows 特有的 bug 吗 😂

我用的是mac，倒是没遇到过这种情况😂
