### ISSUE TITLE
配置 prefix 后 部分样式异常

### ISSUE THREAD

**Issue by dodu2014** [MellowCo/unocss-preset-weapp#31]
在我使用中，配置了前缀，部分样式异常：divide, space, 还有在scss中使用 @apply 也不生效，以为是和 tmui 冲突，就在官方示例 uniapp-vue3 中，引用了tmui，配置前缀前，运行起来是正常的，异常的示例页面：space，divide，apply

配置前缀后，异常的示例页面：space，divide，apply，unocss.config.js 如下：

```js
/**
 * unocss defineConfig
 * @link unocss: https://github.com/unocss/unocss
 * @link unocss-preset-weapp: https://github.com/MellowCo/unocss-preset-weapp
 * */

import { defineConfig, presetIcons } from 'unocss';
import presetWeapp from 'unocss-preset-weapp';
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer';

const transformRules = {
  '.': '-d111-',
  '/': '-s111-',
  ':': '-c111-',
  '%': '-p111-',
  '!': '-e111-',
  '#': '-w111-',
  '(': '-b111l-',
  ')': '-b111r-',
  '[': '-f111l-',
  ']': '-f111r-',
  $: '-r111-',
  ',': '-r222-',
};
const prefix = `uno-`;
const exclude = [/[\\/]node_modules[\\/]/, /[\\/]\.git[\\/]/, /[\\/]dist[\\/]/, /[\\/]tmui[\\/]/];

export default defineConfig({
  // 预设
  presets: [
    // UnoCSS 小程序预设
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp({
      prefix: prefix, // 前缀
      whRpx: true, // wh 是否使用 rpx 为默认单位
      transform: true, // 是否转换微信class
      platform: 'uniapp', // 平台 'taro' | 'uniapp'
      transformRules, // 自定义转换规则
    }),

    // unocss 预设图标配置 https://www.npmjs.com/package/@unocss/preset-icons
    // 按照约定使用图标 <prefix><collection>-<icon> 或者 <prefix><collection>:<icon>
    presetIcons({
      scale: 1.2, // 与当前字体大小（1em）相关的比例。
      warn: true, // 匹配缺少的图标时发出警告
      // prefix: 'i-', // 前缀，默认：i-
    }),
  ],

  // 快捷方式
  shortcuts: [
    {
      'uno-center': 'uno-flex uno-justify-center uno-items-center',
      'uno-border-demo': 'uno-border-2px uno-border-red-500_75 uno-border-solid', // 用于 unocss 示例演示
    },
  ],

  // 规则之间共享配置的主题对象
  // theme: {},

  // 转换器
  transformers: [
    // https://github.com/unocss/unocss/tree/main/packages/transformer-directives
    // transformerDirectives(),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify({
      classPrefix: prefix, // 为生成的class选择器添加前缀, ''
      transformRules, // 自定义转换规则
      nonValuedAttribute: false, // 支持匹配非值属性, true
      // attributes: [], // 需要转换的属性列表, ['bg', 'flex', 'grid', 'border', 'text', 'font', 'class', 'className', 'p', 'm', 'animate']
      exclude, // 排除转换目标, [/[\\/]node_modules[\\/]/, /[\\/]\.git[\\/]/]
      prefix,
      // ignoreNonValuedAttributes: [], // 忽略的非值属性列表, ['class']
      // include: [], // 需要转换的目标, [/\.vue$/,  /\.vue\?vue/]
      prefixedOnly: true, // 仅匹配前缀属性, false
      // transformEscape: true, // 转换转义字符, true
    }),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass({
      transformRules,
      exclude,
    }),
  ],
});

```

在示例页面中修改为 uno-divide-y，uno-space-x-4 等...
就出现了异常：

![image](https://user-images.githubusercontent.com/15245544/216746016-ca9f68f7-cf1a-414a-857f-292587a7d018.png)

![image](https://user-images.githubusercontent.com/15245544/216746035-c3135031-0fc9-431f-8e81-047dc42a4de8.png)

![image](https://user-images.githubusercontent.com/15245544/216746046-eaef7096-6043-4deb-885d-a28eda61c927.png)

**Comment by dodu2014** [comment]
移除 tmui，也是如此；
升级 unocss 至 0.49.4 也是如此；

unocss-preset-weapp 版本为：^0.3.0
看来与其他无关。

**Comment by dodu2014** [comment]
给示例发到了新的分支：https://github.com/dodu2014/unocss-preset-weapp/commit/26926a1a0d78d04c0d02bc30d8220a333ae6c380
以供参考

**Comment by MellowCo** [comment]
这个好像是 unocss prefix 的bug  [playgroup](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCICuA7A9gWgHd8AmABihwIAt8BGCq-AI1wCcQBTN9APmAD04CLwBQoSLEQoMTYuUp58wsF3wBPeooIq1AczadO2fAFYyjJQEJdnZcmqcQfUVCgTo8ZGixKALpwAHn74MMYBbNr4AA6kUbggIABczHr4hs68dILCYm4eUt6y-kEhYdgRUbEkUZwQxilpzHCYnHwkOZB57sKFMr4EAcGh4dxVcUwJyanpTnwAzJ0i4kJdokA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXDhRl1AFxwA2he4DeVGJwC0xpam5kkAiEujnulZG4WAF1gkgM4GAALVBBUc31DQwAjSnkAa0hsGCoEiKS4SVyeAGYAJgAGMEl3fKSqED8ANgAWKprwgsMQZD8AdiaADmrarrglIj8ARgqylpHOrsklabLB9tGu7jLl7mmAVhKmhbrDSWWDo5OC5kXbiIpqWmKLOseaekY9U-JKTEk-PwII5NoZmABKRZhUQQ0RAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

![image](https://user-images.githubusercontent.com/47939250/216750901-d06c3320-35d0-42ff-8697-20d7c9f7a90e.png)

**Comment by MellowCo** [comment]
应该是 space-x 的匹配bug

* 无 prefix
![image](https://user-images.githubusercontent.com/47939250/216752349-0cb3e777-71aa-4bdf-afda-8117440753f1.png)

* 有 prefix
![image](https://user-images.githubusercontent.com/47939250/216752433-3581b7b5-38d1-402f-898e-6410439cc5a5.png)

**Comment by MellowCo** [comment]
添加 `prefix` 导致 `variants` 失效了, 我已经提了一个issues了

```ts
export const variantSpaceAndDivide: Variant = (matcher) => {
  if (/^space-?([xy])-?(-?.+)$/.test(matcher) || matcher.startsWith('divide-')) {
    return {
      matcher,
      selector: (input) => {
        return `${input}>:not([hidden])~:not([hidden])`
      },
    }
  }
}
```

**Comment by dodu2014** [comment]
谢谢，效率很高呢，看到已经修复了，不知道下个版本，上次给你说的tmui的冲突会不会解决

**Comment by MellowCo** [comment]
```shell
npm i unocss-preset-weapp@0.4.0
```

这个版本 space，divide 可以了

**Comment by MellowCo** [comment]
apply 把这个没带 prefix 删除 应该就可以了

![image](https://user-images.githubusercontent.com/47939250/216807027-6543f307-5831-4904-9994-9ae25ec63300.png)

**Comment by dodu2014** [comment]
@MellowCo 谢谢，更新到 0.4 后，space，divide 是修复了，apply 示例，移除了不带前缀的，貌似还是不行。提交的dev的示例也更新了，你可以看下。

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/216878563-5baff050-3bf8-4277-8360-2b4b9e43438e.png)
* 这个自定义转换规则没有 `=`

![image](https://user-images.githubusercontent.com/47939250/216878635-ee48cdd9-1438-43a0-ac32-d1d63b0e8daa.png)

* 这个转换器没开

![image](https://user-images.githubusercontent.com/47939250/216878734-260ff3d0-8378-4a43-861c-ebba000f6499.png)

* --at-apply 会多生成一个 `;` , 把这个 `;` 去掉
![image](https://user-images.githubusercontent.com/47939250/216880617-8271a259-6f17-4008-ac7e-2a4230f998af.png)

**Comment by MellowCo** [comment]
这个应该是 `transformerDirectives` 的bug
![image](https://user-images.githubusercontent.com/47939250/216880744-311f4701-956f-47ef-bd52-a8045321175c.png)
![image](https://user-images.githubusercontent.com/47939250/216880757-17bfe3ab-655a-4e4c-9481-ac613e4d7886.png)

**Comment by MellowCo** [comment]
测试了下，真的会多生成一个 `;`
![image](https://user-images.githubusercontent.com/47939250/216880832-b2d07c20-3add-4374-a22c-06a169892f41.png)
![image](https://user-images.githubusercontent.com/47939250/216880859-66f4ec4f-cc51-4833-9ef0-b7ddc2c32af5.png)

**Comment by dodu2014** [comment]
👍👍👍
确实是，去掉；启用 transformerDirectives 就正常了，= 规则不需要 是正常的

**Comment by MellowCo** [comment]
h5 的 `transformerDirectives ` 有问题，生成出来没有经过 `uniapp css-loader`

![image](https://user-images.githubusercontent.com/47939250/216893650-6df27f1d-3597-4539-81d8-06ec6aa88e7a.png)

**Comment by dodu2014** [comment]
小程序中还有个问题，小程序不支持 * ，而编译后会生成：*,::before,::after{--un-rotate:0;  ...
```css
*,::before,::after{--un-rotate:0;  ... }
```

![image](https://user-images.githubusercontent.com/15245544/216901139-4d9cc5d5-4535-4106-819a-0a1332106059.png)

这个问题怎么解决？

**Comment by MellowCo** [comment]
你用这个配置

```ts
import presetWeapp from 'unocss-preset-weapp'
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer'
import { transformerDirectives } from 'unocss'

export default {
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp(),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      'center': 'flex justify-center items-center',
    },
  ],
  transformers: [
    // https://github.com/unocss/unocss/tree/main/packages/transformer-directives
    transformerDirectives(),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify(),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass(),
  ],
}
```

**Comment by dodu2014** [comment]
用的这个配置：
https://gitee.com/dodu/uniapp-starter/blob/dev/unocss.config.js

**Comment by MellowCo** [comment]
presetUno 生成的

![image](https://user-images.githubusercontent.com/47939250/216902443-ce1cebef-2a09-4a02-ad0b-d9e252d10a41.png)

**Comment by MellowCo** [comment]
你用这个配置就行了，transformRules有默认规则，其他也都有默认值的

```ts
import presetWeapp from 'unocss-preset-weapp'
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer'
import { transformerDirectives } from 'unocss'

const prefix = 'uno-'

export default {
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp({
       prefix
    }),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      'center': 'flex justify-center items-center',
    },
  ],
  transformers: [
    // https://github.com/unocss/unocss/tree/main/packages/transformer-directives
    transformerDirectives(),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify({
      classPrefix: prefix
    }),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass(),
  ],
}
```

**Comment by dodu2014** [comment]
非常感谢，把有些默认值加上去，就是加深印象这里面的一些配置项，现在大多问题都解决了，也学习到很多，再次感谢！

**Comment by MellowCo** [comment]
h5 的 transformerDirectives  有问题的，我先去 uniapp issue那看看怎么解决

**Comment by dodu2014** [comment]
👍 嗯嗯，你是负责任的人
