### ISSUE TITLE
transformerAttributify 配置冲突的问题

### ISSUE THREAD

**Issue by dodu2014** [MellowCo/unocss-preset-weapp#33]
transformerAttributify 配置如下：
```js
transformerAttributify({
      classPrefix: prefix, // 为生成的class选择器添加前缀, ''
      transformRules, // 自定义转换规则
      nonValuedAttribute: true, // 支持匹配非值属性, true
      // attributes: [], // 需要转换的属性列表, ['bg', 'flex', 'grid', 'border', 'text', 'font', 'class', 'className', 'p', 'm', 'animate']
      exclude, // 排除转换目标, [/[\\/]node_modules[\\/]/, /[\\/]\.git[\\/]/]
      prefix,
      // ignoreNonValuedAttributes: [], // 忽略的非值属性列表, ['class']
      // include: [], // 需要转换的目标, [/\.vue$/,  /\.vue\?vue/]
      prefixedOnly: true, // 仅匹配前缀属性, false
      // transformEscape: true, // 转换转义字符, true
    })
```

prefixedOnly 配置为 true，意思是避免和原属性冲突，仅匹配前缀属性。
之前 nonValuedAttribute 为 false，classPrefix 配置为 uno-，`uno-p="3"` 可以生成 `class="uno-p-3"`,
启用非值模式 `nonValuedAttribute: true`，可与有值模式冲突，`<view uno-p-3>` 生成为 `class="uno-uno-p-3"` 无效, classPrefix 设置为 ‘’ 后，`uno-p="3"` 生成的为`class="p-3"` 也无效了。

是不是冲突呢，怎么解决冲突？

我提交的示例：
https://github.com/dodu2014/unocss-preset-weapp/commit/471bdd81555e21bfacf00f35dc679f0dde7a7671

**Comment by dodu2014** [comment]
![image](https://user-images.githubusercontent.com/15245544/217134038-ffd42ed6-befb-4b88-bf1c-8a8fb4572db7.png)

红色无效，绿色有效

**Comment by dodu2014** [comment]
当然 transformerAttributify 下 prefix 为空时，不存在这种冲突

**Comment by MellowCo** [comment]
attributify 不用加 `prefix`

![image](https://user-images.githubusercontent.com/47939250/217138996-9509d6dd-e4e6-43de-acd7-290c720a1d41.png)

**Comment by dodu2014** [comment]
加 prefix 的目的时解决与有些组件属性冲突的问题，例如有个组件有一个 border-bottom 属性，不用 prefix 会引起组件这个属性无效

**Comment by dodu2014** [comment]
之前我把 nonValuedAttribute 设置 false，丢弃了 <view uno-text-sm> 这个模式，想启用，可存在冲突

**Comment by MellowCo** [comment]
这个你可以不加 `uno-xx` 生成css会添加上去的，
![image](https://user-images.githubusercontent.com/47939250/217140685-ffae116a-a026-4529-8350-ecbc8a91e94a.png)

```
# 这个配置就够了
 transformerAttributify({
      classPrefix: 'li-'
    }),
```

**Comment by dodu2014** [comment]
这个我知道，但是加入 view 有个原生属性 bg，值不是这个模式，而是自定义的属性，这样就引起 view bg 属性无效了

**Comment by MellowCo** [comment]
用这个呗 nonValuedAttribute先别用

```ts
 transformerAttributify({
    classPrefix: 'li-',
    prefix,
      prefixedOnly: true
  }),
```

```html
<view li-text="red sm"></view>
```

**Comment by dodu2014** [comment]
嗯，原来就是这样，只是想启用这个模式，那就先这样 😊，非常感谢！！

**Comment by MellowCo** [comment]
nonValuedAttribute 应该是转换时把当前值 (`prefix+className`), 再加 `classPrefix` 了, 应该把 `prefix` 去掉

**Comment by dodu2014** [comment]
是的，你可以给 unocss 提个 issues

**Comment by MellowCo** [comment]
0.4.1 修复了 nonValuedAttribute

**Comment by dodu2014** [comment]
👍👍👍 棒棒哒
