### ISSUE TITLE
原生小程序使用 Attributify 不生效

### ISSUE THREAD

**Issue by zhujiageng** [MellowCo/unocss-preset-weapp#37]
# Thanks
首先非常感谢作者的这个 preset！

# Question
我是用原生小程序开发的，没有使用框架，Attributify 相关的 example 都是 taro 和 uniapp 这种框架，不知道是否支持原生使用这个 transformer 呢？

# code
这个是原生配置了 Attributify 没生效的 demo code，大佬有空帮忙看下，感谢
[demo.zip](https://github.com/MellowCo/unocss-preset-weapp/files/10887365/demo.zip)

**Comment by MellowCo** [comment]
原生使用 transformer 其实是直接修改你的代码文件的 [demo github](https://github.com/MellowCo/unocss-wechat#transformer)


![68747470733a2f2f666173746c792e6a7364656c6976722e6e65742f67682f4d656c6c6f77436f2f696d6167652d686f73742f323032322f3230323230393231323031393332302e676966](https://user-images.githubusercontent.com/47939250/222874233-3ede976c-4530-4a5b-b596-b021a670d324.gif)

**Comment by MellowCo** [comment]
如果没有 webpack 或 vite 环境，不建议使用 transformer

**Comment by MellowCo** [comment]
你的项目 我看了
@unocss/cli 是在 0.45.22 支持的，我运行你的项目 发现是 0.45.21

![image](https://user-images.githubusercontent.com/47939250/222874571-46b2657d-4449-401e-ab8a-fad78adee7ea.png)

重新安装下，就可以了

![image](https://user-images.githubusercontent.com/47939250/222874607-fd572363-328e-4929-be60-fecf0c6c4555.png)

**Comment by MellowCo** [comment]
* unocss.config.js transformerAttributify 添加 include
```js
transformers:[
  transformerAttributify({
    include
  })
]
```


* `transformerAttributify` 只是把 `bg="blue-400"` 转换成 `class="bg-blue-400"` 
> 为了防止多余的转换，按 vue 的 template 语法，只会转换 `template` 下的内容，所以最外层加个 `template`

```html
<template>
  <view>
    <button bg="blue-400" text="xl">
      Attributify
    </button>
    <button class="bg-blue-400 c-_wn_ccc flex flex-1">
      class
    </button>
  </view>
</template>
```

> 但是 `bg="blue-400"` 转换成 `class="bg-blue-400"` 过程中，并不会把 `bg="blue-400"`，所以在 `@unocss/cli` 使用中导致无限循环

![7](https://user-images.githubusercontent.com/47939250/222877625-06fcb377-8ec2-4d75-be00-a4055949ba4c.gif)

所以不建议在 原生小程序 里用 `transformerAttributify`

**Comment by zhujiageng** [comment]
明白了，感谢指导！
