### ISSUE TITLE
Taro dev模式下，修改class自动hot reload不成功，作者有碰到相似问题吗？

### ISSUE THREAD

**Issue by suerta-git** [MellowCo/unocss-preset-weapp#38]
这个问题可能和preset无关，不过似乎其他人集成unocss后也有类似情况（如：https://github.com/NervJS/taro/discussions/11464#discussioncomment-2536093）

不知道作者有没有碰到同样的情况，有解决办法吗？

**Comment by MellowCo** [comment]
> 我试了 webpack4 和 webpack5 但是都没有出现他描述的问题

![10](https://user-images.githubusercontent.com/47939250/224453469-4be6125b-a4a9-4ab1-8d37-05f318b88369.gif)

**Comment by MellowCo** [comment]
这个应该是 taro 的 bug https://github.com/NervJS/taro/issues/12893

我按这个 issue 把微信的热重载关了，就可以了，这个要看 taro 后续的修复

![image](https://user-images.githubusercontent.com/47939250/226073365-15a5368e-04f4-48b6-bfed-07d7d5c621ee.png)

**Comment by suerta-git** [comment]
感谢，看起来是这个原因了，我后续关注那个issue进度。
