### ISSUE TITLE
taro+vue3 跟着配 编译到微信小程序中 样式并未生效

### ISSUE THREAD

**Issue by mz-dfhp** [MellowCo/unocss-preset-weapp#4]

**Comment by MellowCo** [comment]
怎么配置的呢 怎么没生效呢

**Comment by MellowCo** [comment]
unocss 是不是用的 0.45.8 以上版本

**Comment by mz-dfhp** [comment]
![image](https://user-images.githubusercontent.com/63582593/187382585-7aed9ec7-182b-41d3-80e7-eee74254d3f2.png)
![image](https://user-images.githubusercontent.com/63582593/187382611-fcb89bb3-85dd-4ec3-99c1-02ea66a7c42d.png)
![image](https://user-images.githubusercontent.com/63582593/187382758-d10eeeca-adb3-4bbf-8b57-44b5375920e0.png)

**Comment by MellowCo** [comment]
![image](https://user-images.githubusercontent.com/47939250/187384482-6e75f128-bb2f-4860-939d-0925f5b3af0b.png)
@unocss/webpack 使用 0.45.8

0.45.8之后 windows 系统 webpack 有 bug https://github.com/unocss/unocss/issues/1455

**Comment by MellowCo** [comment]
没有其他问题 我要关闭 issue 了

**Comment by mz-dfhp** [comment]
弄好了 谢谢

**Comment by mz-dfhp** [comment]
![image](https://user-images.githubusercontent.com/63582593/188592689-d9145996-dc42-4611-9864-03223c45ef57.png)
![image](https://user-images.githubusercontent.com/63582593/188592774-f56f1c9d-eefb-4c5d-b1ba-4b9540bfe74a.png)
为什么会影响这个文件

**Comment by MellowCo** [comment]
升级到最新版，是unplugin-unocss-attributify-wechat 匹配问题，已经修复了
