### ISSUE TITLE
@apply 报错

### ISSUE THREAD

**Issue by pengyinghao** [MellowCo/unocss-preset-weapp#43]
不能使用@apply 要报错
<img width="788" alt="image" src="https://user-images.githubusercontent.com/34115313/225276176-6396a743-e0c6-4caa-b57b-01069e734ff4.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/34115313/225276229-6fe40144-7a23-44e6-ae63-be4f61322ac5.png">

**Comment by MellowCo** [comment]
https://github.com/unocss/unocss/tree/main/packages/transformer-directives

**Comment by pengyinghao** [comment]
好的谢谢谢

**Comment by van-chin** [comment]
安装了这个 @unocss/transformer-directives 在taro webpack vue3 也会报错

@pengyinghao 你是怎么解决的呢？

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/blob/main/examples/taro_webpack5_react/unocss.config.ts
