### ISSUE TITLE
unocss 主题配置 是否能支持 css 变量

### ISSUE THREAD

**Issue by l1m2e** [MellowCo/unocss-preset-weapp#45]
我定义了以下主题颜色
![image](https://user-images.githubusercontent.com/62976143/227445403-80c269fa-b1e1-4540-98aa-501270807c69.png)
bg-primary 可以正确被识别  bg-primary2 bg-primary3 bg-primary4 均无法被识别
![image](https://user-images.githubusercontent.com/62976143/227445526-67c8d1e8-8273-4cd1-acb7-6ff69c5be33d.png)
![image](https://user-images.githubusercontent.com/62976143/227445660-8d8659c7-abe0-43d1-8dc9-4ee2abb4dcf2.png)

**Comment by MellowCo** [comment]
这个应该去 [unocss](https://github.com/unocss/unocss) 哪，提个issues

**Comment by MellowCo** [comment]
似乎是不支持数字，改成这样就行了
```ts
primaryColor: 'var(--color-primary2)',
```

[playgroup](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBmcCmAPKACwFoBWABiiQAcEYdi9iAWKAWwBcX0qOBPXBmLEYAeziiATsWqSwbBJL4AmAFyScIANzoAfACgoUUJFiIUGAEYBzGXIVKo2fMQCMejvg7AA9OAgGRibQ8Mho6DZ28op8AMLiUk64TO66nnjefpCBxv5mYVa2stFKAMxJLqnpmf4GvrX6QA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZMUAhlletCKlACLBKAYxjAAbtTgBfOOigQQcAOQBXRkKpUlAKG2oAHpFgoMrFQBt4aTDnyFgRABQJtccpRowqALjgBtVzd3aloGCEcAShJAgF1otxZ2Tm5eH39AtwB6TLgACxgYMB9somAYXJUAIwA6IQVMtQgNKgb1TUyWVFRMkFZsTLBWIQBrViJqDrYOLigeKABaZEFUEXFqDLhE6ZT%2BZdWJKkj4uDjA8tQebxcguDrzaB9rm-dQVigAT18lAGIhP6VjjcKK8Pvh7lAvmI3o55vM7tB5sDeh8AEwRAEbNxIt7vADMX0q5hUqAxUkCZKkEW0QA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

**Comment by l1m2e** [comment]
感谢解答  确实是因为数字原因 这个貌似是合理的
