### ISSUE TITLE
单位统一问题

### ISSUE THREAD

**Issue by AshenOneOrz** [MellowCo/unocss-preset-weapp#46]
**首先感谢作者提供的预设**

### 我的问题
[根据文档介绍，本预设仅将 width 和 height 的默认单位设置成了 rpx，其他属性例如 padding margin line-height 等都没有设置](https://github.com/MellowCo/unocss-preset-weapp#%E4%BF%AE%E6%94%B9-w-h-%E9%BB%98%E8%AE%A4%E5%8D%95%E4%BD%8D)

由此产生两个问题
1. 只设置 w 和 h，但其他的值不设置，会不会造成误解？例如这个例子中的 h-100 = 100rpx，而 lh-100 实际上等于 800rpx。在实际开发中我觉得会造成误解（所以来提 Issue），而且会降低编写效率（在写其他值的时候得先做一遍/8的计算，或者在写 wh 的时候先做一遍*8的计算）
```html
<button h-100 lh-100>
    Button
</button>
```
2. 如果我想让其他所有属性和 width & height 保持一致（/8），应该怎么做？

再次感谢~

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp#%E4%BF%AE%E6%94%B9-w-h-%E9%BB%98%E8%AE%A4%E5%8D%95%E4%BD%8D

这里

**Comment by MellowCo** [comment]
lh 和 padding margin 一样基本，都是固定大小递增的，例如 p-2 => padding: 16rpx
你不会希望 p-2 也是 pading=2rpx 吧

**Comment by MellowCo** [comment]
lh 和 padding margin 一样基本，都是固定大小递增的，例如 p-2 => padding: 16rpx
你不会希望 p-2 也是 pading=2rpx 吧

**Comment by MellowCo** [comment]
那你可以加个自定义 `postprocess`

参考这个 [@unocss/preset-rem-to-px](https://github.com/unocss/unocss/blob/main/packages/preset-rem-to-px/src/index.ts)

**Comment by MellowCo** [comment]
感觉覆盖 rules 会好一点

```ts

export default {
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp(),
  ],

  rules: [
    [/^m-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })],
  ],
}

```

![image](https://user-images.githubusercontent.com/47939250/227907158-5da187b2-9151-4c43-85a3-485aa7ef1166.png)
