### ISSUE TITLE
uniapp编译成小程序，%编译异常，如left-50%编译后是left-50

### ISSUE THREAD

**Issue by Yilene** [MellowCo/unocss-preset-weapp#47]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/14181808/228116933-6119979f-852f-49b4-a152-ec6aa6e63f2f.png">

编译后，left-50%变为left-50，而正确应该是编译成：.left-50-pes-

<img width="522" alt="image" src="https://user-images.githubusercontent.com/14181808/228117645-83ce0314-b9a9-4ae7-8658-a3e18dfd60ef.png">

编译配置：
<img width="455" alt="image" src="https://user-images.githubusercontent.com/14181808/228117866-eb8d765a-1817-408f-8eb3-fde7e3fe1b54.png">

**Comment by MellowCo** [comment]
你是 uniapp vue2 还是 vue3，是否有可以重现的案例

![image](https://user-images.githubusercontent.com/47939250/228164994-19dcdeba-19b0-41a2-9489-4d8e11db9637.png)
