### ISSUE TITLE
使用Attributify Mode时，bg-[var(--red-1)]不生效。

### ISSUE THREAD

**Issue by HuangYaobin** [MellowCo/unocss-preset-weapp#48]
![image](https://user-images.githubusercontent.com/51368773/228900730-6bd4e50a-ca57-4206-8141-2814587370e5.png)

![image](https://user-images.githubusercontent.com/51368773/228900556-fd687465-7196-4126-94ae-999ded275567.png)

**Comment by MellowCo** [comment]
因为 Attributify Mode 里不支持匹配 []，可以改为 xx="[xxx]" 性质

```html
<div style="--red-1: red">
  <div class="flex-1" bg-[#ccc] text-center>text</div>
  <div class="flex-1 mt-4" bg="[#aaa]"  text-center>text</div>
  
  <div class="flex-1 mt-4" bg-[var(--red-1)] text-center>text</div>
  <div class="flex-1 mt-4" bg="[var(--red-1)]" text-center>text</div>
</div>
```

[play](https://uno.antfu.me/play/?html=DwEwlgbgBAzgLgTwDYFMC8AiAtFgTikLARgC4p8QMA%2BAKCilEigGMkBDGGTAM1QA9iGKACMA5lgDaAYmayAulDgo%2BcLMxQA7JbipKVwAPTgIteo2isOXDL2XEoAW1UAWIWMzS2XuUMXLV6looOnpwhsamUHQMxizsnDz89k5YriLiEhBsuAAUOBTEAJQKoWqa2rr%2B4ZCR5nFWiXZEji5uoh5ZufkERT5%2BKmVBIVVGNTTVJjRAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZMUAhlletCKlACLBKAYxjAAbtTIVqtAIIwWwAEYBXUegCecOAF846KBBBwA5CsZCqVEwCgbqAB6RYKDKxUAbeGkw58hYCIACgQbbWkaGCoALjgAbTDtckpIhggggEoSRPCUuQUoZTVgTUzEgF1s7RZ2Tm5eGPicuAB6FrgACwUwGLaiYBgOlSUAOiEjFvMISypJiysWllRUFpBWbBawViEAa1YiakW2Di4oHigAWmRBVBFxamaak-r%2BG7uJKkyquErEwdQeNFQkk4OMPNAYsCQclQKwoBpYiYAMRCVEmb4giiw%2BH4cFQRFiOFBC4XMHQC5YtbwgBMGXRzVy2I0AGZEUoPCpUPSdIkeToMjYgA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

![image](https://user-images.githubusercontent.com/47939250/229005787-e6d3afa1-6376-4e20-bd71-5e3aef3a4744.png)

**Comment by MellowCo** [comment]
有这方面需求，可以在 [unocss](https://github.com/unocss/unocss/issues) 提个issues

**Comment by HuangYaobin** [comment]
感谢解答! `text=`这种方式也够用了
