### ISSUE TITLE
作者你好，在uniapp vite 使用字体大小 text-[16px]不生效。

### ISSUE THREAD

**Issue by hiddendeer** [MellowCo/unocss-preset-weapp#49]
(项目目前只涉及到H5), 只能用text-16px这种写法就生效，但是这样会存在写法上的不统一。

**Comment by MellowCo** [comment]
unocss 就是怎么设计的啊 为什么要加 [] 呢

**Comment by MellowCo** [comment]
attributify mode 对 [] 不支持，要转成 xx="[xx]" 这种形式

```html
<div>
  <div class="flex-1 bg-blue" text-[30px] text-center>text</div>
  <div class="flex-1 bg-red mt-4" text="[40px]" text-center>text</div>
</div>
```

[play](https://uno.antfu.me/play/?html=DwEwlgbgfAUABHUk4GMA2BDAzlgvAIgDM0BTADwFoBGOAIwHMLa0BXE-OAF3M4oG0AzAAYADmQC6XHhRQkAdtwBOUbmU7AA9OGjxE21JhwFi5anUaKSIOAFteAFg6rOBPvdESn02QpLLnmtqwgZCwQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZMUAhlletCKlACLBKAYxjAAbtTIVqtAIIwWwAEYBXUegCecOAF846KBBBwA5CsZCqVEwCgbqAB6RYKDKxUAbeGkw58hYCIACgQbbWkaGCoALjgAbTDtckpIhggggEoSRPCUuQUoZTVgTUzEgF1s7RZ2Tm5eGPicuAB6FrgACwUwGLaiYBgOlSUAOiEjFvMISypJiysWllRUFpBWbBawViEAa1YiakW2Di4oHigAWmRBVBFxamaak-r%2BG7uJKkyquErEwdQeNFQkk4OMPNAYsCQclQKwoBpYiYAMRCVEmb4giiw%2BH4cFQRFiOFBC4XMHQC5YtbwgBMGXRzVy2I0AGZEUoPCpUPSdIkeToMjYgA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)


![image](https://user-images.githubusercontent.com/47939250/229005305-23842d46-bf40-4e67-8179-9f313b2bb355.png)

**Comment by MellowCo** [comment]
有这方面需求，可以在 [unocss](https://github.com/unocss/unocss/issues) 提个issues

**Comment by MellowCo** [comment]
类似问题 https://github.com/MellowCo/unocss-preset-weapp/issues/48

**Comment by hiddendeer** [comment]
> attributify mode 对 [] 匹配不支持，要转成 xx="[xx]" 这种形式
> 
> ```
> <div>
>   <div class="flex-1 bg-blue" text-[30px] text-center>text</div>
>   <div class="flex-1 bg-red mt-4" text="[40px]" text-center>text</div>
> </div>
> ```
> 
> [play](https://uno.antfu.me/play/?html=DwEwlgbgfAUABHUk4GMA2BDAzlgvAIgDM0BTADwFoBGOAIwHMLa0BXE-OAF3M4oG0AzAAYADmQC6XHhRQkAdtwBOUbmU7AA9OGjxE21JhwFi5anUaKSIOAFteAFg6rOBPvdESn02QpLLnmtqwgZCwQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZMUAhlletCKlACLBKAYxjAAbtTIVqtAIIwWwAEYBXUegCecOAF846KBBBwA5CsZCqVEwCgbqAB6RYKDKxUAbeGkw58hYCIACgQbbWkaGCoALjgAbTDtckpIhggggEoSRPCUuQUoZTVgTUzEgF1s7RZ2Tm5eGPicuAB6FrgACwUwGLaiYBgOlSUAOiEjFvMISypJiysWllRUFpBWbBawViEAa1YiakW2Di4oHigAWmRBVBFxamaak-r%2BG7uJKkyquErEwdQeNFQkk4OMPNAYsCQclQKwoBpYiYAMRCVEmb4giiw%2BH4cFQRFiOFBC4XMHQC5YtbwgBMGXRzVy2I0AGZEUoPCpUPSdIkeToMjYgA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)
> 
> ![image](https://user-images.githubusercontent.com/47939250/229005305-23842d46-bf40-4e67-8179-9f313b2bb355.png)

因为web端用的tailwindcss，都是用的text-[16px] flex-[1] xx-[] 这样的标准处理，unocss除了text-[16px]不能生效，其它加[]是生效的，就比较好奇为什么。

**Comment by MellowCo** [comment]
你写在class里，是生效的。unocss里也不需要加这个
