### ISSUE TITLE
运行之后在app.wxss中会有一个 *通配符   导致小程序端报错

### ISSUE THREAD

**Issue by sixkong** [MellowCo/unocss-preset-weapp#51]
![image](https://user-images.githubusercontent.com/42209395/231412447-c84f5a4d-90ab-44df-8132-03337d9cf13a.png)
运行之后在app.wxss中会有一个 *通配符   导致小程序端报错

**Comment by sixkong** [comment]
找到问题了，有一点配置搞错了。

**Comment by Mrokor** [comment]
什么配置错误了
