### ISSUE TITLE
uni-app vue2 hmr doesn't work well

### ISSUE THREAD

**Issue by a1mersnow** [MellowCo/unocss-preset-weapp#54]
When you edit some component/page in H5 mode, the hmr doesn't work well, because only the component/page which you are editing is considered as a source change by webpack's HotModuleReplacementPlugin, so the class names update, but the style in App.vue doesn't.

Here is a workaround:

I patch the webpack using the `patch-package`.
Find the `module.hotUpdate = records.moduleHashs[identifier] !== hash;` in `/node_modules/webpack/lib/HotModuleReplacementPlugin.js`, replace it with:
```js
module.hotUpdate = records.moduleHashs[identifier] !== hash || (function () {
  const g = identifier.split('!')
  return g[g.length - 1].includes('src/App.vue?vue&type=style&index=0&lang=css&') && g[0].includes('css-loader')
})();
```
This will force webpack to always consider App.vue as new file.

**Comment by MellowCo** [comment]
So the meaning is, is this the Vue2 webpack hmr solution?

**Comment by a1mersnow** [comment]
It’s a hack trick… I write this for others who want to workaround the hmr problem.
