### ISSUE TITLE
v0.6.0版本在使用时，运行unocss cli watch之后，会在.wxml顶部生成许多注释，导致页面展示出错

### ISSUE THREAD

**Issue by SongYaoLynn** [MellowCo/unocss-preset-weapp#55]
版本信息：
"devDependencies": {
    "unocss": "^0.51.12",
    "unocss-preset-weapp": "^0.6.0"
  }

问题现象如下所示：
![image](https://user-images.githubusercontent.com/26898201/236605968-2b26916e-e4ab-4203-b18e-2c0ea82052ac.png)

**Comment by MellowCo** [comment]
你这是原生小程序使用 transformer 吗

**Comment by SongYaoLynn** [comment]
我是在这个demo的基础上，将unocss-preset-weapp版本升级到^0.6.0，然后执行npm run unocss指令，在.wxml中就会出现截图所示的问题，.wxml中多了很多注释信息
demo：https://github.com/MellowCo/unocss-wechat

**Comment by MellowCo** [comment]
这个是给 unocss vscode 插件，做class位置匹配用的，因为原生小程序使用 transformer 会改变原文件，所以展示出来了 QAQ

**Comment by SongYaoLynn** [comment]
> 这个是给 unocss vscode 插件，做class位置匹配用的，因为原生小程序使用 transformer 会改变原文件，所以展示出来了 QAQ

wow~我尝试降级unocss-preset-weapp到v0.5.3就不会复现问题了，这是0.6.0版本新引入的问题吗？

**Comment by MellowCo** [comment]
* 升级到 0.6.1
```
"unocss-preset-weapp": "^0.6.1"
```

* 添加 `classTags: false`
```ts
transformers: [
  transformerClass({
    include,
    classTags: false
  })
]
```
