### ISSUE TITLE
可以支持百度小程序吗？

### ISSUE THREAD

**Issue by SongYaoLynn** [MellowCo/unocss-preset-weapp#56]
在百度小程序中给 transformer 和 unocss 设置 include包含swan文件之后，最后转换出来的class有误

**Comment by MellowCo** [comment]
没使用过百度小程序，都是用 uniapp 转的

具体错误是什么

**Comment by SongYaoLynn** [comment]
> 没使用过百度小程序，都是用 uniapp 转的
> 
> 具体错误是什么

在百度原生小程序中unocss.config.js的配置信息：
![image](https://user-images.githubusercontent.com/26898201/236612484-4a62cafa-54b0-4566-a65a-cabcef930f95.png)
![image](https://user-images.githubusercontent.com/26898201/236612496-5c450b50-51f9-42a4-a824-223376e3938e.png)

执行unocss cli之后，swan文件（类似微信小程序的wxml）里class的问题：
* 被修改的是注释中的class，非注释组件不生效
* class中变量的.符号被改变，本来不应变动
![image](https://user-images.githubusercontent.com/26898201/236612668-12ef1f26-30eb-4779-82e9-91187d0c63c8.png)

**Comment by MellowCo** [comment]
transformerClass 就是把 class 中 . # : 等字符转换，因为微信小程序不支持 class 中存在这些字符，例如 `bg-#333:30` 需要转换成 `bg-hex333_30`

**Comment by MellowCo** [comment]
你可以不使用 transformerClass ，因为transformerClass 是会改变原文件的，在原生小程序就是玩个乐子

unocss 不像 tailwindcss，单位是不需要用 [] 的，可以直接使用

```html
<view class="h-20px bg-#ccc"></view>
```

**Comment by SongYaoLynn** [comment]
好的！感谢~
