### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by SnowingFox** [MellowCo/unocss-preset-weapp#6]
你好，建议使用monorepo管理项目

**Comment by MellowCo** [comment]
这个哪里需要啊

**Comment by SnowingFox** [comment]
[unocss-preset-weapp](https://github.com/MellowCo/unocss-preset-weapp) - UnoCSS 小程序预设
[unplugin-transform-class](https://github.com/MellowCo/unplugin-transform-class) - class转换插件
[unplugin-attributify-to-class](https://github.com/MellowCo/unplugin-attributify-to-class) - attributify mode to class 插件
[unocss-webpack-uniapp2](https://github.com/MellowCo/unocss-webpack-uniapp2#unocss-webpack-uniapp2) - 兼容 UniApp Vue2 App开发插件

这几个跳来跳去的很麻烦

**Comment by MellowCo** [comment]
[unplugin-transform-class](https://github.com/MellowCo/unplugin-transform-class) 和 [unplugin-attributify-to-class](https://github.com/MellowCo/unplugin-attributify-to-class) 都是 webpack 和 vite 的插件，可以单独使用的，不只是为 unocss-preset-weapp 使用的

[unocss-preset-weapp](https://github.com/MellowCo/unocss-preset-weapp) 里有2个 transformer 可以直接使用
```ts
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer'

export default defineConfig({
  transformers: [
    // options 见https://github.com/MellowCo/unplugin-attributify-to-class
    transformerAttributify(),

    // options 见https://github.com/MellowCo/unplugin-transform-class
    transformerClass(),
  ]
})
```

**Comment by MellowCo** [comment]
[unocss-webpack-uniapp2](https://github.com/MellowCo/unocss-webpack-uniapp2#unocss-webpack-uniapp2) 是以为发现，uniapp vue2 版本，app不能使用 `import ‘unocss’`，为了解决这个问题写的

**Comment by SnowingFox** [comment]
我只是建议一下，因为这些包都是为了同一个目标服务
