### ISSUE TITLE
feat: maybe can support the i-icon 

### ISSUE THREAD

**Issue by zhangmo8** [MellowCo/unocss-preset-weapp#60]

**Comment by MellowCo** [comment]
What do you mean?

**Comment by MellowCo** [comment]
[@unocss/preset-icons ?](https://unocss.dev/presets/icons)

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/b9f060ae-6bf4-43da-b99c-414489ef1d3a)

**Comment by zhangmo8** [comment]
Yep. That's it.
