### ISSUE TITLE
Taro启动Webpack 持久化缓存配置，编译会出现偶发性样式编译失败

### ISSUE THREAD

**Issue by caser993** [MellowCo/unocss-preset-weapp#61]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/127269969/9c2cbf23-84d3-407e-a885-1ca619554dcd)
config/index.js开启该选项，会会出现偶发性样式编译丢失，需要删除依赖重新配置才会正常，麻烦作者帮忙看下有什么配置可兼容

**Comment by MellowCo** [comment]
是否有可重现的案例和问题截图 视频

**Comment by caser993** [comment]
@MellowCo 关闭config->index.js内的`cache.enable: false`
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/127269969/45ddac93-34d0-455e-aef4-4d34aa99277d)

**Comment by caser993** [comment]
> @MellowCo 关闭config->index.js内的`cache.enable: false` ![image](https://user-images.githubusercontent.com/127269969/240239385-45ddac93-34d0-455e-aef4-4d34aa99277d.png)

正常编译成功表现：
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/127269969/70b95222-207d-4628-b974-4b9b9a9c4bf4)
偶发性，可能修改调整5-10次左右会触发一次

**Comment by caser993** [comment]
编译环境：Macos 13.3.1 (a) (22E772610a)
芯片：Apple M2 Max
Taro："@tarojs/taro": "3.6.6"，"@tarojs/cli": "3.6.6"

**Comment by kuonji-arisu** [comment]
我这边也出现了这个问题，打开cache的话有时css会失效

**Comment by MellowCo** [comment]
可能是 @unocss/webpack 插件的问题，unocss 案例中都是禁用 cache 的

https://github.com/unocss/unocss/blob/main/examples/vue-cli5/vue.config.js

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/3e628c8c-15e8-4317-a161-d1d505735bbc)
