### ISSUE TITLE
transformerClass方法转换className时候 不是别className={`text-[#CCCCCC]`}这种语法

### ISSUE THREAD

**Issue by wk1507341428** [MellowCo/unocss-preset-weapp#62]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/19699970/2e4d478d-b2c5-413e-ac16-21a86d921173)

这个getclass方法识别不了 className={`text-[#CCCCCC]`} 还有 className={classnames(`text-[#CCCCCC]`)} 这种写法

**Comment by MellowCo** [comment]
react 是只做了静态 className="xxx" 匹配

**Comment by wk1507341428** [comment]
> react 是只做了静态 className="xxx" 匹配

准备优化一下不？

**Comment by MellowCo** [comment]
这个要足够的测试用例，因为我个人小程序这边不用 react ，没有足够的用例去确定匹配规则。
例如你提到的
```hmtl
className={'xxx'}, className={classnames('xxxx')}
```

**Comment by MellowCo** [comment]
你可以先用以下规则替换 
```
bg-#81ecec/50 => bg-hex-81ecec_50
```

**Comment by MellowCo** [comment]
试试 `unocss-preset-weapp@0.52.1`
