### ISSUE TITLE
请问使用vue-cli vue2 在h5上要刷新才能生效。

### ISSUE THREAD

**Issue by hiddendeer** [MellowCo/unocss-preset-weapp#63]
"unocss": "^0.51.12",
    "unocss-preset-weapp": "^0.6.3",
    "unocss-webpack-uniapp2": "^0.1.4",

按说明都是配置好了，但每次写完后都要手动刷新才能看到效果。

**Comment by MellowCo** [comment]
这个是 unocss hmr 的问题，暂时无解

https://github.com/unocss/unocss/issues?q=hmr

**Comment by MellowCo** [comment]
你可以试试这个
https://github.com/MellowCo/unocss-preset-weapp/issues/54#issue-1680578207
