### ISSUE TITLE
transformerClass VsCode插件报错

### ISSUE THREAD

**Issue by zh-neng** [MellowCo/unocss-preset-weapp#65]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/24434147/398afbff-bf9a-43a9-ae9e-4bcca8966833)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/24434147/809f6512-f76e-41e2-a746-32bacc98a0a4)

**Comment by zh-neng** [comment]
使用环境是  uniapp vite vue3 ts

**Comment by MellowCo** [comment]
你可以调整下顺序 
```
transformers: [
  transformerVariantGroup(),
  transformerDirectives(),
  transformerClass(),
],
```
我在这找了一个相同的错误 https://github.com/unocss/unocss/issues/2566
