### ISSUE TITLE
`bg="pink dark:yellow"` dark 写法不生效

### ISSUE THREAD

**Issue by Ares-Chang** [MellowCo/unocss-preset-weapp#69]
`bg="pink dark:yellow"` 这种写法 dark 模式下 color 不生效

代码块如下：
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/36911513/d4a4736c-4da5-4e63-99b5-2f0617afa745)

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/36911513/c70e327c-3d40-454e-98cb-e31a268add52)

如例， dark 模式分开写没有问题，如果写在一起 dark 字段不会提升到起始。

我尝试阅读了仓库源码，但是有点大，没有修好这个问题。顺带问一下，我看这个包提供了好几个功能了，源码有点大，有考虑过分包嘛？这样好像不是很好阅读

**Comment by MellowCo** [comment]
这是 https://github.com/MellowCo/unplugin-attributify-to-class 提供的功能，目前只支持

```html
<view bg="black" dark:bg="whitte">
```


like this https://github.com/MellowCo/unocss-preset-weapp/issues/50

**Comment by MellowCo** [comment]
经过 [MellowCo/unplugin-attributify-to-class](https://github.com/MellowCo/unplugin-attributify-to-class) 转换，bg="dark:yellow" => class="bg-dark:yellow" 目前没有匹配的规则

**Comment by Ares-Chang** [comment]
thanks

**Comment by MellowCo** [comment]
0.53.2 已支持

**Comment by Ares-Chang** [comment]
Thanks
