### ISSUE TITLE
taro@3.6.7 编辑器保存后，小程序模拟器无法自动刷新，必须手动刷新才能更新样式，有解决方案吗？

### ISSUE THREAD

**Issue by levi-Ma** [MellowCo/unocss-preset-weapp#70]
开发包
{
  "@tarojs/taro": "3.6.7",
  "unocss": "^0.52.5",
  "unocss-preset-weapp": "^0.52.1",
  "webpack": "^5.78.0"
}；

如题

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/issues/38 

是不是这个问题

**Comment by levi-Ma** [comment]
可以了。

**Comment by levi-Ma** [comment]
这都快半年了
