### ISSUE TITLE
taro @apply 属性名称未知

### ISSUE THREAD

**Issue by 38888** [MellowCo/unocss-preset-weapp#71]
小程序 h5 都这样子 也有可能我没配置对。。
或者说 这种不支持taro

**Comment by MellowCo** [comment]
https://github.com/unocss/unocss/tree/main/packages/transformer-directives

**Comment by MellowCo** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/781f0f27-a30d-40b4-a6c1-ea8b50055114)

**Comment by 38888** [comment]
好了好了，感谢。前端小白新入坑
