### ISSUE TITLE
apply 没有被解析 

### ISSUE THREAD

**Issue by 38888** [MellowCo/unocss-preset-weapp#72]
taro-react

![1686713317244](https://github.com/MellowCo/unocss-preset-weapp/assets/110122298/ea1ce3fb-5678-43a4-bbf2-c18b85e8f1dd)
没有被解析

上个issues搞错了

**Comment by MellowCo** [comment]
你可以在 unocss 的 issues 中找到答案
https://github.com/unocss/unocss/issues/2195

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/taro_webpack5_react
