### ISSUE TITLE
使用Attributify 编辑器没有提示

### ISSUE THREAD

**Issue by xuuui** [MellowCo/unocss-preset-weapp#73]

**Comment by Ares-Chang** [comment]
可以在 VSCode 中安装一下 UnoCSS 的 [扩展](https://marketplace.visualstudio.com/items?itemName=antfu.unocss) ，点击链接或者在插件中搜索 `antfu.unocss` ，使用方法可以参考 [文档](https://unocss.dev/integrations/vscode#unocss-vs-code-extension) ，但是这个插件经常不确定性失灵。如果介意可以再安一个 WindiCSS 的扩展。

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/36911513/6e11ff07-388b-4c78-9fc2-ab42de1c99d0)

**Comment by MellowCo** [comment]
我觉得你应该添加图片或详细的描述，便于其他人理解你要传递的信息

**Comment by HuangYaobin** [comment]
<img width="398" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/51368773/cd4378cf-a10e-41b9-b4b5-00313a92a151">
这样写没有提示

**Comment by MellowCo** [comment]
> 

https://github.com/MellowCo/unocss-preset-weapp#attributify-autocomplete-v0531

**Comment by MellowCo** [comment]
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/51368773/262683169-cd4378cf-a10e-41b9-b4b5-00313a92a151.png"> 这样写没有提示

https://github.com/MellowCo/unocss-preset-weapp#attributify-autocomplete-v0531

**Comment by HuangYaobin** [comment]
<img width="1528" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/51368773/a02ad5aa-cb53-4350-820d-7e1fe01a23f4">
好像不行

**Comment by MellowCo** [comment]
> <img alt="image" width="1528" src="https://user-images.githubusercontent.com/51368773/262820356-a02ad5aa-cb53-4350-820d-7e1fe01a23f4.png"> 好像不行

你是指下划线 还是输入提示。下划线的话，目前做不到，unocss里直接固定了，没有适配transform的配置

**Comment by HuangYaobin** [comment]
> > <img alt="image" width="1528" src="https://user-images.githubusercontent.com/51368773/262820356-a02ad5aa-cb53-4350-820d-7e1fe01a23f4.png"> 好像不行
> 
> 你是指下划线 还是输入提示。下划线的话，目前做不到，unocss里直接固定了，没有适配transform的配置

噢，我以为可以出现下划线，如上配置，是有输入提示的。
