### ISSUE TITLE
实测 现在uniapp-vue2完全不能用

### ISSUE THREAD

**Issue by zccl** [MellowCo/unocss-preset-weapp#74]
咋回事呀 麻烦解答下
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22192098/20aebdd7-db06-44b2-b5f1-d0c96cf09e0c)

**Comment by MellowCo** [comment]
"unocss": "0.51.12",
"unocss-preset-weapp": "0.6.3",
"unocss-webpack-uniapp2": "0.1.4",

降下版本

**Comment by zccl** [comment]
实在感谢作者~
