### ISSUE TITLE
uniapp 有使用scss 怎么办 运行报错了

### ISSUE THREAD

**Issue by zccl** [MellowCo/unocss-preset-weapp#75]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22192098/c4ef9cee-18c2-41ef-a860-264410dc4248)

**Comment by zccl** [comment]
安装 node-sass不成功 太老了

**Comment by MellowCo** [comment]
这个和unocss无关的吧 百度改个scss版本就行了

**Comment by zccl** [comment]
确实 还是多谢多谢~
