### ISSUE TITLE
热更新js不生效

### ISSUE THREAD

**Issue by zccl** [MellowCo/unocss-preset-weapp#76]
修改html css 热更新 但是修改js不生效 页面会刷新(因为我点击切换的状态会恢复到初始状态) 但是改的js 不生效 重新编译才行 然后我试了hbuilder是没问题的 我用你这个示例就不中 一开始css也不更新的 我按照issues里面有个英文回复的改下就可以更新了
大佬 这是咋回事哟
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22192098/fb051bb2-0099-40b4-bb2e-a5304b93505e)

**Comment by zccl** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22192098/1d5c6a82-c734-46e0-a962-7edf28d7a601)

**Comment by zccl** [comment]
关闭这个就可以诶 为什么
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/22192098/973af9ee-4027-451b-8191-580637e46c86)

**Comment by MellowCo** [comment]
我好像没有把这个选项打开过，之前打开项目经常不刷新。应该是机制问题，taro和uniapp都有这个问题
