### ISSUE TITLE
怎么忽略动态类名转换

### ISSUE THREAD

**Issue by wyq0201** [MellowCo/unocss-preset-weapp#77]
`<view class="{{item.status === '0' ? 'btn-time ' : 'btn-time-active'}}" wx:for="{{workTimes}}">`
被保存成
`<view class="{{item_dl_status _eqe__eqe__eqe_ '0' ? 'btn-time ' _cl_ 'btn-time-active'}}" wx:for="{{workTimes}}">`

**Comment by wyq0201** [comment]
谢谢，可以了

**Comment by wyq0201** [comment]
这样子好像会有个新的问题，比如rounded-1/2，同样无法转化了。  请问还有其他的办法吗

**Comment by wyq0201** [comment]
已解决，感谢

issues上传图片抽风，之前对

_原生小程序使用` transformer 会改变原文件，不推荐使用
@unocss/cli 在 [0.45.22](https://github.com/unocss/unocss/releases/tag/v0.45.22) 版本支持使用 transformer_

这段话理解错误，以为是在0.45.22可以在小程序中使用没问题了。
之前已经使用了unocss-preset-weapp，不过没用hex或者_转义
测试使用active:转义成active_不生效，不清楚是不是操作方法不当
目前使用的方法是去掉了transformers设置，#使用hex转义，1/2使用half或者1_2，/ 好像使用的也很少，active:或者hover:在shortcuts中配置了一些常用的，在shortcuts中使用不需要转义

**Comment by MellowCo** [comment]
小程序里会用到 hover: active: 吗？
能提供一段代码吗

**Comment by wyq0201** [comment]
可用，多谢~
