### ISSUE TITLE
line-clamp 这个貌似在小程序中没有转换...而且不会高亮显示。

### ISSUE THREAD

**Issue by djkloop** [MellowCo/unocss-preset-weapp#78]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/21050914/5f8d9b0f-b846-40ad-98e2-91a13e3c772f)
```shell
    "unocss": "^0.53.3",
    "unocss-preset-weapp": "^0.53.2",
    "@unocss/preset-icons": "^0.53.3",
```
#### unocss.config.js
```js
/**
 * unocss defineConfig
 * @link unocss: https://github.com/unocss/unocss
 * @link unocss-preset-weapp: https://github.com/MellowCo/unocss-preset-weapp
 * */

import { defineConfig, presetIcons } from 'unocss'
import presetWeapp from 'unocss-preset-weapp'
import { transformerAttributify, transformerClass } from 'unocss-preset-weapp/transformer'

const transformRules = {
  '.': '-d111-',
  '/': '-s111-',
  ':': '-c111-',
  '%': '-p111-',
  '!': '-e111-',
  '#': '-w111-',
  '(': '-b111l-',
  ')': '-b111r-',
  '[': '-f111l-',
  ']': '-f111r-',
  $: '-r111-',
  ',': '-r222-',
}

const prefix = `_u_`

export default defineConfig({
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp({
      nonValuedAttribute: true,
      prefix: prefix,
      whRpx: true,
      transform: true,
      platform: 'uniapp',
      transformRules,
    }),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      '_u_z-tar-both': '_u_z-988',
      '_u_head-fixed': '_u_fixed _u_top-0 _u_left-0 _u_w-full _u_z-tar-both',
      _u_center: '_u_flex _u_justify-center _u_items-center',
    },
  ],
  theme: {},
  transformers: [
    transformerAttributify({
      classPrefix: prefix,
      transformRules,
      nonValuedAttribute: true,
    }),
    transformerClass({
      transformRules,
    }),
  ],
})
```

#### 在unocss playground确实支持line-clamp 地址↓
demo link[DEMO LINK](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcQJAFRcQtaLW0lAFVWAGEAZSzFbWAAenAIZJ1iqBYABwBmKUxcfBQAc0ozWrq1CygUYKxCFE41SrgAJlLtABUYDmDaDEEvcRAsDWIQKABBDBY1MAIobKyoEibegDopmaF50griOGXV9a2dvYOc4%2BJT9gvpqFmbot7o9BM9trt9odPt8sL8rnMFncHitQZtwW8oSdzpd-tdEUsUWs0a9IR8sT8cQD8cDCWCSe8juTYZS8bcCU9iRCGdDznkdEVIONdOoRpRqDgoAArJBzMAIACehBI5HqBhGJgqNTqMBYECwZAAvAAiKoADikRvGOk4fJS-0InDIznuKBYTRYcFOGBgSEctpS%2BnwwWmZBE-u0MDIWAQxpgGAwlVoPAKBS9PscZ38agKrhYBFotBzrHztCN4aU8zITSwGGNAH1HANiABrMt2qCyQqaW2FYrJXuC%2BQDkpD8qcRy0FgoJDYKDOeM7IxQUNNONwOrUBD4OqBpWkfWa2qtdrJdmogDtuIRt0vyDQ8qgBBl6IAXuPqEOBSUgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4XyA)

**Comment by MellowCo** [comment]
加上了，升级到 `0.53.3`

**Comment by djkloop** [comment]
@MellowCo 感谢，高效率
