### ISSUE TITLE
不支持filter、backdrop-filter么？

### ISSUE THREAD

**Issue by Jonathan143** [MellowCo/unocss-preset-weapp#80]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/26000743/c6e304f9-88fc-401b-a8a1-603ecf8b025c)

```
backdrop-filter backdrop-blur-40 // 没有生效
```

**Comment by MellowCo** [comment]
有些小程序不常用就没加，这个有用的给你加一个

**Comment by MellowCo** [comment]
加上了 0.53.4

**Comment by Jonathan143** [comment]
> 加上了 0.53.4

可以用了 感谢
