### ISSUE TITLE
input 组件 `placeholder` 导致后续 class 解析失败

### ISSUE THREAD

**Issue by Ares-Chang** [MellowCo/unocss-preset-weapp#81]
复现方法：

在样式前写入 `input` 并带有 `placeholder` 属性。

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/36911513/6aadfb29-9fdf-4bc5-bea3-e2983efe1893)

期待结果：

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/36911513/ac9bbc32-c38e-40da-8e98-c925aafaa86e)

现在结果：

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/36911513/fa7cc56f-6c66-4bef-b737-0a7c77aa5656)

现有解决方法：

移除 `placeholder` 属性，可解决这个问题。

**Comment by Ares-Chang** [comment]
这是我通过 uni-app cli 新建的项目，只引入了 `unocss-preset-weapp` 和 `unocss` 两个插件。

只需要设置 `<input type="text" placeholder="What's your name?">` 就可以复现。

**Comment by MellowCo** [comment]
update 0.53.5

**Comment by MellowCo** [comment]
const elementRE = /<\w(?=.*>)[\w:\.$-]*\s((?:['"`].*?['"`]|.*?)*?)>/gs

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/6856a969-b16b-4597-a9b6-09df30f38ae8)

正则的匹配问题

**Comment by Ares-Chang** [comment]
Thanks ，了解了
