### ISSUE TITLE
丰富 `Attributify` 可用属性，对标 `UnoCSS` 使用方法

### ISSUE THREAD

**Issue by Ares-Chang** [MellowCo/unocss-preset-weapp#82]
您好，非常感谢提供了 unocss attributify 转译小程序的插件。

我在使用插件的过程中发现其中有一大部分属性及组合方式无法直接使用，比如 `color="pink"`  等等方法无法实现。

虽然可以分开来写，但是对比一下，和部分 UnoCSS 使用方式写法不一致，导致学习成本大增加。

我在写的时候发现，其实部分功能是可以实现的，比如 `bg='pink'` 、`p='20'` 等待方法是可以实现的。

**Comment by MellowCo** [comment]
加 `attributes` 就行了

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/cc7cb0b2-af12-46d5-9b38-b8e4c4f591a6)

**Comment by Ares-Chang** [comment]
是的，可以自定义管理，但是我感觉这个是不是应该兼容 unocss 写法，而不是把这个抛给用户解决。

如果想要自己定义什么规则这个方法是非常好的。

**Comment by Ares-Chang** [comment]
但是我觉得这应该不是一个好的方法，因为如果要维护好一个拼接的字段集，需要了解所有的 css 名称和连接。

是否还有别的方法呢？

**Comment by MellowCo** [comment]
小程序不支持 `attributify css`的, 这个是 `transformer` 啊

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/a9765c57-40dc-4600-a1e0-500492f3a767)

**Comment by Ares-Chang** [comment]
抱歉，我没理解你的意思，或者我上面的意思表达不明确。

我现在写 `color='pink'` 我是想得到 `color-pink` 结果的，小程序不支持 `attributify` 所以这个结果还需要变成 `class="color-pink"` 这样。

但是现在的包并不支持，不应该说只支持部分属性如 `p,m,text...` 等等

**Comment by MellowCo** [comment]
这些都是单属性啊 color-颜色

**Comment by Ares-Chang** [comment]
sorry, 我们应该集中到一个 issues 上讨论，请移到 [7](https://github.com/MellowCo/unplugin-attributify-to-class/pull/7) 这里我给到了答案，感谢。
