### ISSUE TITLE
taro react  自定义Tabbar  样式不生效

### ISSUE THREAD

**Issue by mwj610** [MellowCo/unocss-preset-weapp#83]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52907799/f978e4c8-24e2-4b72-a416-db926e8d574a)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52907799/6fd70301-8355-446e-b83b-40c762c29c1d)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/52907799/8b4d5d25-7a6d-4bff-8066-0b2f94308c8d)

**Comment by MellowCo** [comment]
这个是taro的问题吧，之前有人遇到了
https://github.com/MellowCo/unocss-preset-weapp/issues/44
