### ISSUE TITLE
uniapp-vue2 中怎么使用 @apply

### ISSUE THREAD

**Issue by de1ck** [MellowCo/unocss-preset-weapp#85]
目前没有发现有什么方案可以使用

**Comment by de1ck** [comment]
目前用 postcss-windcss 方案替换

**Comment by MellowCo** [comment]
加个这个，我react里实现了

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/acce847a-2499-48a6-bad2-3c84fbfe412b)

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp/blob/main/examples/taro_webpack5_react/unocss.config.ts

**Comment by de1ck** [comment]
> transformerDirectives 对于webpack好像是有问题的
> 
> https://github.com/MellowCo/unocss-preset-weapp/blob/ceed87940b65f0136cd73b9ed9d4d944ed90381d/examples/taro_webpack5_react/unocss.config.ts#L21C1-L26

是的 webpack 下不行，unocss directives 还不支持webpack下使用

**Comment by MellowCo** [comment]
加上 pre 是可以的，我在react demo中实现了

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/b1ebc581-2682-4056-ab4d-478e94133ce0)

**Comment by de1ck** [comment]
> 加上 pre 是可以的，我在react demo中实现了
> 
> ![image](https://user-images.githubusercontent.com/47939250/251112883-b1ebc581-2682-4056-ab4d-478e94133ce0.png)

试过了，在uniapp_vue2下不会转化
