### ISSUE TITLE
uniapp-vue2配置不生效～

### ISSUE THREAD

**Issue by Zhenhaobo** [MellowCo/unocss-preset-weapp#86]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/69471169/73a74deb-ac15-4d82-8d06-d3ea4472d600)
这句话怎么理解呢 在style  @import 'uno.css';这样子引入吗
我按照教程配置 看起来没有效果～ 
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/69471169/0467264b-44a5-4e7d-89de-50b6bab42aec)

**Comment by MellowCo** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/6b89e393-10ab-484c-8433-9082fd7fd52c)

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-webpack-uniapp2#%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/a5c4e332-7209-40c1-9c0e-ab264f489f4e)

**Comment by Zhenhaobo** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/69471169/4a09289d-e1ae-4753-b71d-3b44a182db75)
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/69471169/80d8899e-de58-4643-b710-9f9ea1bf9228)

一模一样 大佬

**Comment by MellowCo** [comment]
提供demo

**Comment by MellowCo** [comment]
是不是什么版本的问题

**Comment by Zhenhaobo** [comment]
https://gitcode.net/weixin_56243314/appTest   git链接 大佬帮忙看看
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/69471169/c80400bb-9f9a-4f66-969c-af1f1f6f9dd0)
版本的话 就这么一点东西

**Comment by MellowCo** [comment]
你这个hbuilder创的项目，我都是用 cli 创建的，hbuilder内置的node兼容性好像挺差的

**Comment by Zhenhaobo** [comment]
大佬你是用的cli创建到 vscode的项目吗 好吧～  那我下次在创建项目时 再看看

**Comment by MellowCo** [comment]
可以的
```shell
# 创建uni-app
vue create -p dcloudio/uni-preset-vue my-project
```
