### ISSUE TITLE
配置 isH5 为 true 时，解析错误

### ISSUE THREAD

**Issue by github-lxb** [MellowCo/unocss-preset-weapp#87]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/51040135/b3f12b71-b6c7-4fc9-9b48-9235520b6cd1)

**Comment by MellowCo** [comment]
你是用的是 vue2 还是 vue3 呢

**Comment by github-lxb** [comment]
vue3版的

**Comment by MellowCo** [comment]
vue3 参照 https://github.com/MellowCo/unocss-preset-weapp/tree/main/examples/uniapp_vue3

不需要写 isH5 ，vite loader 已经转换单位了
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/eb23d01a-27a5-4677-b51f-6489dee5a581)

**Comment by github-lxb** [comment]
好的，谢谢
