### ISSUE TITLE
uniapp 中功能类解析出错

### ISSUE THREAD

**Issue by github-lxb** [MellowCo/unocss-preset-weapp#88]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/51040135/ad8fa90b-6668-4ebc-942b-d52130ae7f24)

.w-10：解析为 0.3125rem，最终的px值为 5px,这个是没问题
.m-10：解析为 2.5rem，最终的px值为 40px，这个就解析的有问题

平台：uniapp
vue版本：vue3
unocss-preset-weapp版本：0.53.5

**Comment by MellowCo** [comment]
![Screenshot_2023-07-17-17-07-37-643_com.github.android.jpg](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/9f779853-bf0f-4e53-bbfd-e21b81bd6a3a)

**Comment by MellowCo** [comment]
或者自己改下规则

'''
export default {
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp(),
  ],

  rules: [
    [/^m-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })],
  ],
}
'''

**Comment by github-lxb** [comment]
> ![Screenshot_2023-07-17-17-07-37-643_com.github.android.jpg](https://user-images.githubusercontent.com/47939250/253897036-9f779853-bf0f-4e53-bbfd-e21b81bd6a3a.jpg)

目前 whRpx 是默认的 true，改为 false 不是我想要的结果😅, 例如上面的问题，.m-1 希望生成的样式为 `margin: 1rpx`, 这1rpx最终会被 uniapp 转换为对应的 rem

**Comment by github-lxb** [comment]
> 或者自己改下规则
> 
> ''' export default { presets: [ // https://github.com/MellowCo/unocss-preset-weapp presetWeapp(), ],
> 
> rules: [ [/^m-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })], ], } '''

这个要自定义的话太多了，比如 p-10, 我也得定义这个规则，有没有什么快捷的办法呀

**Comment by MellowCo** [comment]
H5上就是rem单位啊。 小程序才会是rpx

**Comment by github-lxb** [comment]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/51040135/97a6605c-96af-4952-8c50-2545c006a22d)
这是小程序环境，发现解析还是有问题

**Comment by MellowCo** [comment]
unocss 就是在于可以自定义的优点的 可以自己修改。

**Comment by MellowCo** [comment]
你把config截个图看看

**Comment by github-lxb** [comment]
> 你把config截个图看看

刚发现小程序解析失败的原因是我配置有问题，我把 isH5 设置为 true 了

**Comment by MellowCo** [comment]
> > 或者自己改下规则
> > ''' export default { presets: [ // https://github.com/MellowCo/unocss-preset-weapp presetWeapp(), ],
> > rules: [ [/^m-(\d)$/, ([, d]) => ({ margin: `${d}rpx` })], ], } '''
> 
> 这个要自定义的话太多了，比如 p-10, 我也得定义这个规则，有没有什么快捷的办法呀

这个就是习惯问题，不可能满足所有人的，但是unocss可以自定义，也是优点之一
