### ISSUE TITLE
vue2项目中，添加插件后编译速度巨慢

### ISSUE THREAD

**Issue by fanyuwei4** [MellowCo/unocss-preset-weapp#90]

**Comment by MellowCo** [comment]
有多慢😂

**Comment by fanyuwei4** [comment]
> 有多慢😂

我用tailwindcss那个编译时间是20秒以内，然后换unocss编译要超过1分钟了；而且w-20识别为width-20rpx，但是mt-20会识别为margin-top:160rpx

**Comment by MellowCo** [comment]
单位的问题可以使用 https://github.com/MellowCo/unocss-preset-weapp#%E4%BF%AE%E6%94%B9-w-h-%E9%BB%98%E8%AE%A4%E5%8D%95%E4%BD%8D 解决，将 w-20 改为与 mt 相同的计算逻辑

**Comment by MellowCo** [comment]
编译的问题可能要具体项目分析，我判断不了是哪方面的原因。可能可以再优化下transform的性能

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/05cccd4f-8513-4e19-8a5d-925445d9ee8b)

**Comment by MellowCo** [comment]
0.53.7 加了cache，我测试了之前的项目，不加unocss要40秒，加了unocss也就慢了6s。你这个差了40s也太夸张了吧
