### ISSUE TITLE
space-y-x 会报错

### ISSUE THREAD

**Issue by x-end** [MellowCo/unocss-preset-weapp#91]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/108337284/92d305b1-dadc-4867-92ef-a838d44d2e83)

**Comment by MellowCo** [comment]
这个是你混用了 `presetWind` 的问题吧 去掉就好了

**Comment by x-end** [comment]
[unocss-preset-weapp](https://github.com/MellowCo/unocss-preset-weapp) 里包含了 presetWind 的功能吗？

**Comment by MellowCo** [comment]
大部分有吧

**Comment by MellowCo** [comment]
space-x 特别针对小程序做了兼容的
