### ISSUE TITLE
box-shadow 连体写法无法工作

### ISSUE THREAD

**Issue by CharleeWa** [MellowCo/unocss-preset-weapp#92]
@MellowCo 作者好，如下：

- unocss: latest
- unocss-preset-weapp: latest
- ide: vscode + wechat devtools

```
<view class="w-120rpx h-100rpx shadow-[0rpx_6rpx_20rpx_0rpx_rgba(237,_237,_237,_1)]"></view>
```

ps. box-shadow 预设可以工作，但是自定义连体写法无法工作。

**Comment by MellowCo** [comment]
自定义是什么样的呢

**Comment by CharleeWa** [comment]
> 自定义是什么样的呢

非预设，连体写法：

```
<view class="shadow-[0px_4px_4px_0px_rgba(237,_0,_0,_1)]"></view>
```

**Comment by MellowCo** [comment]
可以啊 

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/42f39769-5c88-4080-af52-cd5c9afca440)

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/12f16e5b-6890-44c0-8d40-6ca738bd1339)

**Comment by MellowCo** [comment]
你page上有些信息吗

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/ff700a73-b8b4-4d9a-80a8-6c2cc033911f)

**Comment by CharleeWa** [comment]
@MellowCo  有的

**Comment by MellowCo** [comment]
改成黑背景是不是就行了呢

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/b41bc659-6860-4745-9438-4b9ffaaea926)

**Comment by CharleeWa** [comment]
好像是这个问题，但是为什么会这样？

编辑器里的：
```
  <view class="w-full h-488rpx bg-hex-ffffff rounded-24rpx box-border p-24rpx shadow-[0rpx_6rpx_20rpx_0rpx_rgba(237,_0,_0,_1)]">
```

浏览器里的 class ：
![1690791102733](https://github.com/MellowCo/unocss-preset-weapp/assets/22477554/6d4728db-11e5-4e73-b3ae-2b36ff1ef8ce)

编译后的 class（unocss.wxss ）：
![1690791126330](https://github.com/MellowCo/unocss-preset-weapp/assets/22477554/ac4bc660-f49d-4140-8f4d-8b741724cd46)

**Comment by MellowCo** [comment]
你是什么平台的

**Comment by MellowCo** [comment]
你是原生小程序的吗，原生小程序好像是没什么办法，因为不能走 transformer

**Comment by CharleeWa** [comment]
是原生小程序

**Comment by MellowCo** [comment]
> 是原生小程序

这个就是平台限制了，原生小程序是没什么办法的

**Comment by CharleeWa** [comment]
怪我没描述清楚，我以为咱这个预设就是给原生小程序准备的呢，所以没写上平台。好的，我先用style解决。谢谢

**Comment by CharleeWa** [comment]
喔喔，不过我试了其他都挺好用的，像是 `#` 写为 `hex` 这样,  bg-hex-ededed。如果不支持这个地方，我想在readme中 补充关于`box-shadow`在原生小程序不支持。您看怎么描述更规范具体一些？

**Comment by MellowCo** [comment]
加在这里吧 https://github.com/MellowCo/unocss-wechat

**Comment by CharleeWa** [comment]
好的

**Comment by vaynevayne** [comment]
原生小程序不支持中括号变量？
