### ISSUE TITLE
unocss样式在小程序和h5项目的区别

### ISSUE THREAD

**Issue by Soumns777** [MellowCo/unocss-preset-weapp#93]
我在正常的项目中用 b="4 solid red rd-sm" ,可以正常展示盒子的border颜色 border-radius,但是在小程序里面用的时候就没有用,是我需要进行什么配置吗?

**Comment by MellowCo** [comment]
1. 使用 border
```html
border="4 solid red rd-sm"
```

2. 加一个 attributes [link](https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify#attributify-mode)
```ts
const { presetWeappAttributify, transformerAttributify } = extractorAttributify({
  attributes: [...defaultAttributes, 'b'],
})

export default {
  presets: [
    // https://github.com/MellowCo/unocss-preset-weapp
    presetWeapp(),
    // attributify autocomplete
    presetWeappAttributify(),
    presetIcons(),
  ],
  shortcuts: [
    {
      'border-base': 'border border-gray-500_10',
      'center': 'flex justify-center items-center',
    },
  ],
  transformers: [
    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
    transformerAttributify(),

    // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
    transformerClass(),
  ],
}
```

**Comment by MellowCo** [comment]
b 不在默认的属性里

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/adbda2bb-4e32-4c1f-8ce9-beb414176f15)

**Comment by Soumns777** [comment]
非常感谢,这两种方法我试了一下都是可以的,还想另外问一个问题就是,小程序里面我如果直接写 w-100 h-100  mt-100的时候不会自动解析成rpx,这种有可以配置的地方自动解析吗?

**Comment by MellowCo** [comment]
https://github.com/MellowCo/unocss-preset-weapp#%E4%BF%AE%E6%94%B9-w-h-%E9%BB%98%E8%AE%A4%E5%8D%95%E4%BD%8D

**Comment by Soumns777** [comment]
mt-100 这个我没开whRpx:true也是会给我弄成 margin-top:800rpx,这个是正常情况吗?

**Comment by Soumns777** [comment]
ok 我来试试,多谢

**Comment by Soumns777** [comment]
<img width="316" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/332e3b14-88b2-471b-878c-e06804e0d8b4">

<img width="627" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/cedd795a-cf60-4a21-8fd8-f6eddce2b6cc">


你好,我配置了你上面写的,然后用了m-20,编译出来还是margin:160rpx,是我哪里配错了嘛

**Comment by MellowCo** [comment]
你是怎么配的 config.ts

**Comment by MellowCo** [comment]
https://unocss.dev/config/rules

**Comment by newbie-dingdong** [comment]
发现class使用单引号不会转义 双引号可以

**Comment by newbie-dingdong** [comment]
> 发现class使用单引号不会转义 双引号可以

应该说是有需要转义的class时 比如class='text-[#f00]'

**Comment by MellowCo** [comment]
> > 发现class使用单引号不会转义 双引号可以

这个代码规范的问题吧 加个eslint 或者 prettier 格式化，统一就行了

**Comment by Soumns777** [comment]
import presetWeapp from 'unocss-preset-weapp'
    import {defaultAttributes, extractorAttributify, transformerClass} from 'unocss-preset-weapp/transformer'
    import {
      presetUno,
    } from 'unocss';
    
    const {presetWeappAttributify, transformerAttributify} = extractorAttributify({
      attributes: [...defaultAttributes, 'b'],
    })
    
    
    export default {
      presets: [
        // https://github.com/MellowCo/unocss-preset-weapp
        presetWeapp({
          // whRpx: true,
        }),
        presetWeappAttributify(),
      ],
      theme: {
        colors: {
          base: '#fff', // 白色
        },
        boxShadow: {
          '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
        },
        borderRadius: {
          'sm': '10px 10px 0 0'
        }
      },
    
      rules: [
        [/^m-(\d)$/, ([, d]) => ({margin: `${d}rpx`})],
      ],
      shortcuts: [
        // 动态颜色
        [
          /^s-btn-(.*)$/,
          ([, c]) =>
              `bg-${c}-400 text-${c}-100  py-2 px-4  font-semibold rounded-lg shadow-md  border-none  cursor-pointer text-center`,
        ],
    
        // flex样式布局
        [
          /^f-((c|s|e)(-(c|s|e|b|a))*)$/,
          ([, , g1, , g2]) => {
            let style = ``;
            const temps = [
              {k: "c", v: "center"},
              {k: "s", v: "start"},
              {k: "e", v: "end"},
              {k: "b", v: "between"},
              {k: "a", v: "around"}
            ];
    
            const r1 = temps.find(i => i.k == g1);
            style = `flex items-${r1?.v || "center"} content-${r1?.v || "center"}`;
    
            if (g2) {
              const r2 = temps.find(i => i.k == g2);
              style += ` justify-${r2?.v || "center"}`;
            }
    
            return style;
          }
        ]
      ],
      transformers: [
        // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerAttributify
        transformerAttributify(),
    
        // https://github.com/MellowCo/unocss-preset-weapp/tree/main/src/transformer/transformerClass
        transformerClass(),
      ]
    }
    

这个是我的unocss.config.js的配置,方便看一下吗?

**Comment by MellowCo** [comment]
可以啊 你是哪个平台的，我用的 uniapp_vue3

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/42cbb480-177b-4b59-8e87-17d6b87abea0)

**Comment by Soumns777** [comment]
我也是用的uniapp-vue3啊,好奇怪,可能区别是不是我是命令行创建的项目呢

<img width="794" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/42f5f3c0-4445-4303-befe-0d1ac98ce4b6">
<img width="328" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/972f2c4b-43ad-420b-b54c-97c39459f32b">
<img width="332" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/ec3f73a8-5c9b-47f6-bc84-89353ee599d0">

**Comment by MellowCo** [comment]
正则的问题, 加个*

```
 rules: [
    [/^m-(\d*)$/, ([, d]) => ({ margin: `${d}rpx` })],
  ],
```

**Comment by Soumns777** [comment]
ok 现在好了,那如果我想写m-t-20还得配个上面的正则[/^mt-(\d*)$/, ([, d]) => ({ margin-top: `${d}rpx` })],这样子吗,有没有方便可以给几个margin整合在一块的方法,哈哈

**Comment by MellowCo** [comment]
```ts
  rules: [
    [/^m(t|b|l|r*)-(\d*)$/, ([, t, d]) => {
      const map = {
        t: 'top',
        b: 'bottom',
        l: 'left',
        r: 'right',
      }
      return ({ [t ? `margin-${map[t]}` : 'margin']: `${d}rpx` })
    }],
  ],
```

**Comment by Soumns777** [comment]
okok 我来试试,多谢

**Comment by Soumns777** [comment]
小程序里面如果我只加了一个margin-top的话,为什么按钮会直接在页面中间了呢?这个是小程序自带的button的样式吗 ?
<img width="325" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/ccc70a0e-0675-4926-bb9f-367da675b831">

**Comment by Soumns777** [comment]
哦哦 这个貌似是小程序自带的样式,需要手动给清除一下
