### ISSUE TITLE
[提问] 可以支持mpx吗？

### ISSUE THREAD

**Issue by iamcyw** [MellowCo/unocss-preset-weapp#95]
大神可以考虑下出个mpx的例子吗？

**Comment by MellowCo** [comment]
没用过mpx 如果是webpack 应该是能用

**Comment by iamcyw** [comment]
> 没用过mpx 如果是webpack 应该是能用

按照unocss的webpack集成试了下，编译报错，所有看看大神有没有意向，没有就关了

**Comment by MellowCo** [comment]
目前没有 对mpx不了解
