### ISSUE TITLE
Uniapp+Vue2提示 PostCSS plugin tailwindcss requires PostCSS 8

### ISSUE THREAD

**Issue by Soumns777** [MellowCo/unocss-preset-weapp#96]
为什么我在Uniapp+Vue2的项目里面引入unocss,然后编辑器会提示我 PostCSS plugin tailwindcss requires PostCSS 8,当我按照网上的一个文档下载postcss@7之后编辑部再报错,但是微信小程序里面打不开组件了。当我按照https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users这个解决方案的时候,还是没有解决问题,想问下这个是什么问题呢？

**Comment by Soumns777** [comment]
<img width="1036" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/fd102e64-1bf6-47ec-92e3-b5f6e5618ca0">
<img width="460" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/ca611f72-0e6c-4155-a59c-2d57e5b6fc4c">
<img width="336" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/cccd22ba-6cf3-40fb-b35a-6f7b05698896">
我重新创建了一个小程序项目,uniapp+unocss,配置完成以后发现并没有生效,如果看见的话还请回复一下,感谢。

**Comment by MellowCo** [comment]
给个demo地址吧

**Comment by Soumns777** [comment]
刚刚好像又可以了,稍等我给关了吧,报一丝

**Comment by Soumns777** [comment]
刚刚那个新创建的项目引入是正常的,之前的uniapp+vue2的项目引入我刚刚试了引入确实会报错 PostCSS plugin postcss-uniapp-plugin requires PostCSS 8,我在想是哪个依赖需要更新一下来着？

**Comment by Soumns777** [comment]
<img width="1105" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/ef9243b1-f3d6-4d76-a93c-95425a215baa">

**Comment by Soumns777** [comment]
如果方便的话还请帮忙看下呢，感谢。

**Comment by MellowCo** [comment]
有demo地址吗

**Comment by MellowCo** [comment]
我想起来了unocss之前加了个postcss模块，应该是 postcss 版本不兼容了，你升级下postcsss插件应该就行了

https://github.com/unocss/unocss/tree/main/packages/postcss

**Comment by Soumns777** [comment]
我看我的项目没有用到@unocss/postcss这个插件啊,也是需要更新这个模块的吗?

**Comment by MellowCo** [comment]
现在来看是要更新的

**Comment by Soumns777** [comment]
我刚刚试了按照https://unocss.dev/integrations/postcss这个流程以后启动项目还是会报下面的错误,这个是因为导入unocss导致的吗?
<img width="821" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/d44748df-3bd7-4dcb-a124-3e0c37c2074f">

**Comment by MellowCo** [comment]
> 我刚刚试了按照[https://unocss.dev/integrations/postcss这个流程以后启动项目还是会报下面的错误,这个是因为导入unocss导致的吗](https://unocss.dev/integrations/postcss%E8%BF%99%E4%B8%AA%E6%B5%81%E7%A8%8B%E4%BB%A5%E5%90%8E%E5%90%AF%E5%8A%A8%E9%A1%B9%E7%9B%AE%E8%BF%98%E6%98%AF%E4%BC%9A%E6%8A%A5%E4%B8%8B%E9%9D%A2%E7%9A%84%E9%94%99%E8%AF%AF,%E8%BF%99%E4%B8%AA%E6%98%AF%E5%9B%A0%E4%B8%BA%E5%AF%BC%E5%85%A5unocss%E5%AF%BC%E8%87%B4%E7%9A%84%E5%90%97)? <img alt="image" width="821" src="https://user-images.githubusercontent.com/63893877/260607541-d44748df-3bd7-4dcb-a124-3e0c37c2074f.png">

这个意思就是让你升级 postcss 到 8 ，因为 unocss 用的 8

**Comment by Soumns777** [comment]
<img width="415" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/91807477-96f7-4aa4-bc02-094345c04749">

<img width="664" alt="image" src="https://github.com/MellowCo/unocss-preset-weapp/assets/63893877/b88af5ab-ae14-4d0d-9fd2-6c1c247bc6f0">
我按照官网这个指引来操作的,还是会报上面那个错误,奇奇怪怪

**Comment by MellowCo** [comment]
https://github.com/dcloudio/uni-app/issues/4127

https://github.com/dcloudio/uni-app/issues?q=PostCSS+8

uniapp issue可以参考下吧，看来是 uniapp 的问题了

**Comment by MellowCo** [comment]
你把unocss去掉 看看是不是还报错

**Comment by Soumns777** [comment]
我昨天试了给unocss去掉之后 项目是正常打开的,我再来用这个帖子里面yarn安装依赖的方式再试下吧

**Comment by Soumns777** [comment]
我试了原始的代码里面没有unocss是可以正常运行的,但是加了unocss就莫名其妙报错,但是当我用最新的cli创建uniapp的模板的时候引入unocss又可以正常使用了,所以我现在也很懵😳

**Comment by MellowCo** [comment]
这个没有重现demo 我应该猜不出来什么问题
