### ISSUE TITLE
unocss 的vscode插件更新到0.55.1后，样式不会下滑线高亮了，鼠标hover也没有tooptip展示

### ISSUE THREAD

**Issue by cl1107** [MellowCo/unocss-preset-weapp#97]
unocss 的vscode插件更新到0.55.1后，样式不会下滑线高亮了，鼠标hover也没有tooptip展示

1、更新项目unocss到0.55.1无法解决问题
2、降级vscode的unocss插件到0.54.3能临时解决问题

**Comment by MellowCo** [comment]
这个是unocss插件的问题呢  https://github.com/unocss/unocss/issues/2993

**Comment by MellowCo** [comment]
执行下reload 就可以了呢

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/47939250/9813cc6d-01c0-438c-be2b-b4f9fe6a079c)
