### ISSUE TITLE
`divide-y-0`和`divide-x-0`没有生效

### ISSUE THREAD

**Issue by zam157** [MellowCo/unocss-preset-weapp#98]
![image](https://github.com/MellowCo/unocss-preset-weapp/assets/24277775/5bc53aa0-7cd9-41d1-b4ac-3d8ca6c95ad0)

原因是`calc(0 * 1px)`是不合法的, 应该改成`calc(0px * 1px)`

作为对比unocss的默认preset这里是没问题的

![image](https://github.com/MellowCo/unocss-preset-weapp/assets/24277775/5d7f32f3-79a1-4217-9eab-0632d0e293d4)

**Comment by MellowCo** [comment]
0.55.2 修复了
